// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_world_event_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_world_event_type.proto</summary>
  public static partial class EnumWorldEventTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_world_event_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumWorldEventTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtlbnVtX3dvcmxkX2V2ZW50X3R5cGUucHJvdG8SBnpwcm90byr7BAoOV29y",
            "bGRFdmVudFR5cGUSDQoJQ2hhbmdlQmdtEAASDQoJTm90aWNlVGlwEAESEAoM",
            "Qm9zc0ZpZ2h0Q2FtEAISFAoQRXhpdEJvc3NGaWdodENhbRADEhAKDFBsYXlD",
            "dXRTY2VuZRAEEhAKDFNjcmVlbkVmZmVjdBAFEhEKDU5wY0J1YmJsZUNoYXQQ",
            "BhIPCgtTZXRDYW1QaXRjaBAHEgwKCFBhdXNlQ2FtEAgSDwoLU2hvd0VudHJ5",
            "VUkQChIZChVXb3JsZEV2ZW50U3dpdGNoTGF5ZXIQCxIWChJQbGF5TGlnaHRB",
            "bmltYXRpb24QDBIWChJTd2l0Y2hQYXlQb2ludE1vdmUQDRITCg9TZXRNb3Zl",
            "RGlyTGltaXQQDhIMCghQbGF5RmxvdxAPEg4KCkR1bmdlb25UaXAQEBIXChND",
            "YW1lcmFDb25maWdSZXBsYWNlEBESEQoNTnBjSGFuZEluSGFuZBASEg4KClZv",
            "bHVtZUN0cmwQExIVChFTZXRDYW1Mb29rQXRQb2ludBAUEhAKDENhbWVyYUlu",
            "dm9rZRAVEg4KClNjcmVlbkZhZGUQFhIYChRTd2l0Y2hDYW1lcmFUZW1wbGF0",
            "ZRAXEh8KG0NyZWF0ZUNsaWVudEVudGl0aWVzQnlHcm91cBAYEh8KG0RlbGV0",
            "ZUNsaWVudEVudGl0aWVzQnlHcm91cBAZEhcKE1NldEVudGl0eVNoYWRvd0Rh",
            "cmsQGhITCg9QbGF5TGV2ZWxFZmZlY3QQGxIYChROZXh0RHVuZ2VvbkNvdW50",
            "RG93bhAcEgsKB0Jvc3NEQk0QHRIYChRJbnZva2VDYW1lcmFUZW1wbGF0ZRAe",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.WorldEventType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum WorldEventType {
    [pbr::OriginalName("ChangeBgm")] ChangeBgm = 0,
    [pbr::OriginalName("NoticeTip")] NoticeTip = 1,
    [pbr::OriginalName("BossFightCam")] BossFightCam = 2,
    [pbr::OriginalName("ExitBossFightCam")] ExitBossFightCam = 3,
    [pbr::OriginalName("PlayCutScene")] PlayCutScene = 4,
    [pbr::OriginalName("ScreenEffect")] ScreenEffect = 5,
    [pbr::OriginalName("NpcBubbleChat")] NpcBubbleChat = 6,
    [pbr::OriginalName("SetCamPitch")] SetCamPitch = 7,
    [pbr::OriginalName("PauseCam")] PauseCam = 8,
    [pbr::OriginalName("ShowEntryUI")] ShowEntryUi = 10,
    [pbr::OriginalName("WorldEventSwitchLayer")] WorldEventSwitchLayer = 11,
    [pbr::OriginalName("PlayLightAnimation")] PlayLightAnimation = 12,
    [pbr::OriginalName("SwitchPayPointMove")] SwitchPayPointMove = 13,
    [pbr::OriginalName("SetMoveDirLimit")] SetMoveDirLimit = 14,
    [pbr::OriginalName("PlayFlow")] PlayFlow = 15,
    [pbr::OriginalName("DungeonTip")] DungeonTip = 16,
    [pbr::OriginalName("CameraConfigReplace")] CameraConfigReplace = 17,
    [pbr::OriginalName("NpcHandInHand")] NpcHandInHand = 18,
    [pbr::OriginalName("VolumeCtrl")] VolumeCtrl = 19,
    [pbr::OriginalName("SetCamLookAtPoint")] SetCamLookAtPoint = 20,
    [pbr::OriginalName("CameraInvoke")] CameraInvoke = 21,
    [pbr::OriginalName("ScreenFade")] ScreenFade = 22,
    [pbr::OriginalName("SwitchCameraTemplate")] SwitchCameraTemplate = 23,
    [pbr::OriginalName("CreateClientEntitiesByGroup")] CreateClientEntitiesByGroup = 24,
    [pbr::OriginalName("DeleteClientEntitiesByGroup")] DeleteClientEntitiesByGroup = 25,
    [pbr::OriginalName("SetEntityShadowDark")] SetEntityShadowDark = 26,
    [pbr::OriginalName("PlayLevelEffect")] PlayLevelEffect = 27,
    [pbr::OriginalName("NextDungeonCountDown")] NextDungeonCountDown = 28,
    [pbr::OriginalName("BossDBM")] BossDbm = 29,
    [pbr::OriginalName("InvokeCameraTemplate")] InvokeCameraTemplate = 30,
  }

  #endregion

}

#endregion Designer generated code
