// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_item_package_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_item_package_type.proto</summary>
  public static partial class EnumEItemPackageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_item_package_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEItemPackageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5lbnVtX2VfaXRlbV9wYWNrYWdlX3R5cGUucHJvdG8SBnpwcm90byqlAgoQ",
            "RUl0ZW1QYWNrYWdlVHlwZRIPCgtQYWNrYWdlTm9kZRAAEg8KC1BhY2thZ2VJ",
            "dGVtEAESEAoMUGFja2FnZUVxdWlwEAISDwoLUGFja2FnZVNpZ24QBRISCg5Q",
            "YWNrYWdlRmFzaGlvbhAHEhUKEVBhY2thZ2VXZWFwb25Ta2luEAgSFwoTUGFj",
            "a2FnZVBlcnNvbmFsWm9uZRAJEhgKFFBhY2thZ2VVbmlvblJlc291cmNlEAoS",
            "FAoQUGFja2FnZUZ1cm5pdHVyZRALEg8KC1BhY2thZ2VSaWRlEAwSGwoXUGFj",
            "a2FnZUhvbWVMYW5kQ3VycmVuY3kQDRITCg9QYWNrYWdlQ3VycmVuY3kQZBIV",
            "ChFQYWNrYWdlTGlmZUNhcmVlchBmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EItemPackageType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EItemPackageType {
    [pbr::OriginalName("PackageNode")] PackageNode = 0,
    [pbr::OriginalName("PackageItem")] PackageItem = 1,
    [pbr::OriginalName("PackageEquip")] PackageEquip = 2,
    [pbr::OriginalName("PackageSign")] PackageSign = 5,
    [pbr::OriginalName("PackageFashion")] PackageFashion = 7,
    [pbr::OriginalName("PackageWeaponSkin")] PackageWeaponSkin = 8,
    [pbr::OriginalName("PackagePersonalZone")] PackagePersonalZone = 9,
    [pbr::OriginalName("PackageUnionResource")] PackageUnionResource = 10,
    [pbr::OriginalName("PackageFurniture")] PackageFurniture = 11,
    [pbr::OriginalName("PackageRide")] PackageRide = 12,
    [pbr::OriginalName("PackageHomeLandCurrency")] PackageHomeLandCurrency = 13,
    [pbr::OriginalName("PackageCurrency")] PackageCurrency = 100,
    [pbr::OriginalName("PackageLifeCareer")] PackageLifeCareer = 102,
  }

  #endregion

}

#endregion Designer generated code
