// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_action_group_track_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_action_group_track_type.proto</summary>
  public static partial class EnumEActionGroupTrackTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_action_group_track_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEActionGroupTrackTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRlbnVtX2VfYWN0aW9uX2dyb3VwX3RyYWNrX3R5cGUucHJvdG8SBnpwcm90",
            "byo5ChVFQWN0aW9uR3JvdXBUcmFja1R5cGUSEAoMRUFjdGlvblRyYWNrEAAS",
            "DgoKRUZhY2VUcmFjaxABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EActionGroupTrackType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EActionGroupTrackType {
    [pbr::OriginalName("EActionTrack")] EactionTrack = 0,
    [pbr::OriginalName("EFaceTrack")] EfaceTrack = 1,
  }

  #endregion

}

#endregion Designer generated code
