// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_mahjong_config_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_mahjong_config_type.proto</summary>
  public static partial class EnumMahjongConfigTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_mahjong_config_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumMahjongConfigTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5lbnVtX21haGpvbmdfY29uZmlnX3R5cGUucHJvdG8SBnpwcm90byqGBAoR",
            "TWFoam9uZ0NvbmZpZ1R5cGUSFQoRTWFoam9uZ0NvbmZpZ051bGwQABIjCh9N",
            "YWhqb25nQ29uZmlnUGxheWVyVGhpbmtUaW1lU2VjEAESIQodTWFoam9uZ0Nv",
            "bmZpZ0Jhc2VUaGlua1RpbWVTZWMQAhIeChpNYWhqb25nQ29uZmlnU3RhcnRC",
            "YXNlQ29pbhADEi4KKk1haGpvbmdDb25maWdUYWJsZVdhaXRDbGllbnRMb2Fk",
            "aW5nVGltZVNlYxAEEiwKKE1haGpvbmdDb25maWdUYWJsZUlubmVyU2V0dGxl",
            "V2FpdFRpbWVTZWMQBRInCiNNYWhqb25nQ29uZmlnVGFibGVTZXR0bGVZYWt1",
            "QWRkVGltZRAGEhwKGE1haGpvbmdDb25maWdTY29yZVBvaW50cxAHEh8KG01h",
            "aGpvbmdDb25maWdCb251c1JhbmtQb2ludBAIEh8KG01haGpvbmdDb25maWdD",
            "b2luQ29udmVyc2lvbhAJEiAKHE1haGpvbmdDb25maWdZYWt1bWFuU2hvd1Rp",
            "bWUQChIbChdNYWhqb25nQ29uZmlnR21UZXN0RmxhZxALEh8KG01haGpvbmdD",
            "b25maWdQbGF5ZXJFeGl0VGltZRAMEisKJ01haGpvbmdDb25maWdQbGF5ZXJU",
            "aW1lbGVzc0RlbGF5VGltZVNlYxANYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.MahjongConfigType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MahjongConfigType {
    [pbr::OriginalName("MahjongConfigNull")] MahjongConfigNull = 0,
    [pbr::OriginalName("MahjongConfigPlayerThinkTimeSec")] MahjongConfigPlayerThinkTimeSec = 1,
    [pbr::OriginalName("MahjongConfigBaseThinkTimeSec")] MahjongConfigBaseThinkTimeSec = 2,
    [pbr::OriginalName("MahjongConfigStartBaseCoin")] MahjongConfigStartBaseCoin = 3,
    [pbr::OriginalName("MahjongConfigTableWaitClientLoadingTimeSec")] MahjongConfigTableWaitClientLoadingTimeSec = 4,
    [pbr::OriginalName("MahjongConfigTableInnerSettleWaitTimeSec")] MahjongConfigTableInnerSettleWaitTimeSec = 5,
    [pbr::OriginalName("MahjongConfigTableSettleYakuAddTime")] MahjongConfigTableSettleYakuAddTime = 6,
    [pbr::OriginalName("MahjongConfigScorePoints")] MahjongConfigScorePoints = 7,
    [pbr::OriginalName("MahjongConfigBonusRankPoint")] MahjongConfigBonusRankPoint = 8,
    [pbr::OriginalName("MahjongConfigCoinConversion")] MahjongConfigCoinConversion = 9,
    [pbr::OriginalName("MahjongConfigYakumanShowTime")] MahjongConfigYakumanShowTime = 10,
    [pbr::OriginalName("MahjongConfigGmTestFlag")] MahjongConfigGmTestFlag = 11,
    [pbr::OriginalName("MahjongConfigPlayerExitTime")] MahjongConfigPlayerExitTime = 12,
    [pbr::OriginalName("MahjongConfigPlayerTimelessDelayTimeSec")] MahjongConfigPlayerTimelessDelayTimeSec = 13,
  }

  #endregion

}

#endregion Designer generated code
