// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_mahjong_protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_mahjong_protocol.proto</summary>
  public static partial class EnumMahjongProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_mahjong_protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumMahjongProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtlbnVtX21haGpvbmdfcHJvdG9jb2wucHJvdG8SBnpwcm90byrTAQoPTWFo",
            "am9uZ1Byb3RvY29sEhcKE01haGpvbmdQcm90b2NvbE5vbmUQABIICgRTeW5j",
            "EAESDwoLU3luY09wZXJhdGUQAhIQCgxTeW5jVGFibGVFbmQQAxISCg5TeW5j",
            "U2hvd1NldHRsZRAEEhMKD1N5bmNGaW5hbFNldHRsZRAFEhUKEVN5bmNQbGF5",
            "ZXJNZXNzYWdlEAYSEwoPU3luY1BsYXllckVtb2ppEAcSCgoGSGFuZGxlEGUS",
            "CwoHQ29uZmlybRBmEgwKCFRlc3RDYXJkEG5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.MahjongProtocol), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MahjongProtocol {
    [pbr::OriginalName("MahjongProtocolNone")] None = 0,
    [pbr::OriginalName("Sync")] Sync = 1,
    [pbr::OriginalName("SyncOperate")] SyncOperate = 2,
    [pbr::OriginalName("SyncTableEnd")] SyncTableEnd = 3,
    [pbr::OriginalName("SyncShowSettle")] SyncShowSettle = 4,
    [pbr::OriginalName("SyncFinalSettle")] SyncFinalSettle = 5,
    [pbr::OriginalName("SyncPlayerMessage")] SyncPlayerMessage = 6,
    [pbr::OriginalName("SyncPlayerEmoji")] SyncPlayerEmoji = 7,
    [pbr::OriginalName("Handle")] Handle = 101,
    [pbr::OriginalName("Confirm")] Confirm = 102,
    [pbr::OriginalName("TestCard")] TestCard = 110,
  }

  #endregion

}

#endregion Designer generated code
