// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_login_plat_form_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_login_plat_form_type.proto</summary>
  public static partial class EnumLoginPlatFormTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_login_plat_form_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumLoginPlatFormTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9lbnVtX2xvZ2luX3BsYXRfZm9ybV90eXBlLnByb3RvEgZ6cHJvdG8qyQEK",
            "EUxvZ2luUGxhdEZvcm1UeXBlEhEKDUlubmVyUGxhdEZvcm0QABITCg9UZW5j",
            "ZW50UGxhdEZvcm0QARIQCgxJbnRsUGxhdEZvcm0QAhITCg9IYW9QbGF5UGxh",
            "dEZvcm0QAxIPCgtBcGpQbGF0Rm9ybRAEEg4KClhkUGxhdEZvcm0QBRIZChVT",
            "b3V0aGVhc3RBc2lhUGxhdEZvcm0QBhIVChBMb2dpblBsYXRGb3JtTWF4EOcH",
            "EhIKDUFpQm90UGxhdEZvcm0Qj05iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.LoginPlatFormType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LoginPlatFormType {
    [pbr::OriginalName("InnerPlatForm")] InnerPlatForm = 0,
    [pbr::OriginalName("TencentPlatForm")] TencentPlatForm = 1,
    [pbr::OriginalName("IntlPlatForm")] IntlPlatForm = 2,
    [pbr::OriginalName("HaoPlayPlatForm")] HaoPlayPlatForm = 3,
    [pbr::OriginalName("ApjPlatForm")] ApjPlatForm = 4,
    [pbr::OriginalName("XdPlatForm")] XdPlatForm = 5,
    [pbr::OriginalName("SoutheastAsiaPlatForm")] SoutheastAsiaPlatForm = 6,
    [pbr::OriginalName("LoginPlatFormMax")] LoginPlatFormMax = 999,
    [pbr::OriginalName("AiBotPlatForm")] AiBotPlatForm = 9999,
  }

  #endregion

}

#endregion Designer generated code
