// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_level_editor_pos_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_level_editor_pos_type.proto</summary>
  public static partial class EnumELevelEditorPosTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_level_editor_pos_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumELevelEditorPosTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJlbnVtX2VfbGV2ZWxfZWRpdG9yX3Bvc190eXBlLnByb3RvEgZ6cHJvdG8q",
            "1gEKE0VMZXZlbEVkaXRvclBvc1R5cGUSGwoXTGV2ZWxFZGl0b3JQb3NUeXBl",
            "QmFzaWMQABIdChlMZXZlbEVkaXRvclBvc1R5cGVQb2ludElkEAESHAoYTGV2",
            "ZWxFZGl0b3JQb3NUeXBlRW50aXR5EAISGQoVTGV2ZWxFZGl0b3JQb3NUeXBl",
            "UG9zEAMSIAocTGV2ZWxFZGl0b3JQb3NUeXBlUG9pbnRHcm91cBAEEigKJExl",
            "dmVsRWRpdG9yUG9zVHlwZVBvaW50R3JvdXBOb25SZXBldBAFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ELevelEditorPosType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ELevelEditorPosType {
    [pbr::OriginalName("LevelEditorPosTypeBasic")] LevelEditorPosTypeBasic = 0,
    [pbr::OriginalName("LevelEditorPosTypePointId")] LevelEditorPosTypePointId = 1,
    [pbr::OriginalName("LevelEditorPosTypeEntity")] LevelEditorPosTypeEntity = 2,
    [pbr::OriginalName("LevelEditorPosTypePos")] LevelEditorPosTypePos = 3,
    [pbr::OriginalName("LevelEditorPosTypePointGroup")] LevelEditorPosTypePointGroup = 4,
    [pbr::OriginalName("LevelEditorPosTypePointGroupNonRepet")] LevelEditorPosTypePointGroupNonRepet = 5,
  }

  #endregion

}

#endregion Designer generated code
