// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_get_team_info_reply.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_get_team_info_reply.proto</summary>
  public static partial class StruGetTeamInfoReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_get_team_info_reply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruGetTeamInfoReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zdHJ1X2dldF90ZWFtX2luZm9fcmVwbHkucHJvdG8SBnpwcm90bxoXZW51",
            "bV9lX2Vycm9yX2NvZGUucHJvdG8aGHN0cnVfdGVhbV9hY3Rpdml0eS5wcm90",
            "bxoZc3RydV90ZWFtX2Jhc2VfaW5mby5wcm90bxolc3RydV90ZWFtX21lbWJl",
            "cl9mYXN0X3N5bmNfZGF0YS5wcm90bxoYc3RydV90ZWFtX21lbV9kYXRhLnBy",
            "b3RvGihzdHJ1X3RlYW1fbWVtX3JlYWxfdGltZV92b2ljZV9pbmZvLnByb3Rv",
            "Io8FChBHZXRUZWFtSW5mb1JlcGx5EicKCWJhc2VfaW5mbxgBIAEoCzIULnpw",
            "cm90by5UZWFtQmFzZUluZm8SKAoLbWVtYmVyX2RhdGEYAiADKAsyEy56cHJv",
            "dG8uVGVhbU1lbURhdGESKwoNdGVhbV9hY3Rpdml0eRgDIAEoCzIULnpwcm90",
            "by5UZWFtQWN0aXZpdHkSVgoZbWVtX3JlYWxfdGltZV92b2ljZV9pbmZvcxgE",
            "IAMoCzIzLnpwcm90by5HZXRUZWFtSW5mb1JlcGx5Lk1lbVJlYWxUaW1lVm9p",
            "Y2VJbmZvc0VudHJ5Ej4KDG1lbV92b2ljZV9pZBgGIAMoCzIoLnpwcm90by5H",
            "ZXRUZWFtSW5mb1JlcGx5Lk1lbVZvaWNlSWRFbnRyeRJPChVtZW1iZXJfZmFz",
            "dF9zeW5jX2RhdGEYByADKAsyMC56cHJvdG8uR2V0VGVhbUluZm9SZXBseS5N",
            "ZW1iZXJGYXN0U3luY0RhdGFFbnRyeRIkCghlcnJfY29kZRgIIAEoDjISLnpw",
            "cm90by5FRXJyb3JDb2RlGl4KGk1lbVJlYWxUaW1lVm9pY2VJbmZvc0VudHJ5",
            "EgsKA2tleRgBIAEoAxIvCgV2YWx1ZRgCIAEoCzIgLnpwcm90by5UZWFtTWVt",
            "UmVhbFRpbWVWb2ljZUluZm86AjgBGjEKD01lbVZvaWNlSWRFbnRyeRILCgNr",
            "ZXkYASABKAMSDQoFdmFsdWUYAiABKAU6AjgBGlkKF01lbWJlckZhc3RTeW5j",
            "RGF0YUVudHJ5EgsKA2tleRgBIAEoAxItCgV2YWx1ZRgCIAEoCzIeLnpwcm90",
            "by5UZWFtTWVtYmVyRmFzdFN5bmNEYXRhOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEErrorCodeReflection.Descriptor, global::Zproto.StruTeamActivityReflection.Descriptor, global::Zproto.StruTeamBaseInfoReflection.Descriptor, global::Zproto.StruTeamMemberFastSyncDataReflection.Descriptor, global::Zproto.StruTeamMemDataReflection.Descriptor, global::Zproto.StruTeamMemRealTimeVoiceInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.GetTeamInfoReply), global::Zproto.GetTeamInfoReply.Parser, new[]{ "BaseInfo", "MemberData", "TeamActivity", "MemRealTimeVoiceInfos", "MemVoiceId", "MemberFastSyncData", "ErrCode" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetTeamInfoReply : pb::IMessage<GetTeamInfoReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetTeamInfoReply> _parser = new pb::MessageParser<GetTeamInfoReply>(() => new GetTeamInfoReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetTeamInfoReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruGetTeamInfoReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetTeamInfoReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetTeamInfoReply(GetTeamInfoReply other) : this() {
      baseInfo_ = other.baseInfo_ != null ? other.baseInfo_.Clone() : null;
      memberData_ = other.memberData_.Clone();
      teamActivity_ = other.teamActivity_ != null ? other.teamActivity_.Clone() : null;
      memRealTimeVoiceInfos_ = other.memRealTimeVoiceInfos_.Clone();
      memVoiceId_ = other.memVoiceId_.Clone();
      memberFastSyncData_ = other.memberFastSyncData_.Clone();
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetTeamInfoReply Clone() {
      return new GetTeamInfoReply(this);
    }

    /// <summary>Field number for the "base_info" field.</summary>
    public const int BaseInfoFieldNumber = 1;
    private global::Zproto.TeamBaseInfo baseInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.TeamBaseInfo BaseInfo {
      get { return baseInfo_; }
      set {
        baseInfo_ = value;
      }
    }

    /// <summary>Field number for the "member_data" field.</summary>
    public const int MemberDataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Zproto.TeamMemData> _repeated_memberData_codec
        = pb::FieldCodec.ForMessage(18, global::Zproto.TeamMemData.Parser);
    private readonly pbc::RepeatedField<global::Zproto.TeamMemData> memberData_ = new pbc::RepeatedField<global::Zproto.TeamMemData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zproto.TeamMemData> MemberData {
      get { return memberData_; }
    }

    /// <summary>Field number for the "team_activity" field.</summary>
    public const int TeamActivityFieldNumber = 3;
    private global::Zproto.TeamActivity teamActivity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.TeamActivity TeamActivity {
      get { return teamActivity_; }
      set {
        teamActivity_ = value;
      }
    }

    /// <summary>Field number for the "mem_real_time_voice_infos" field.</summary>
    public const int MemRealTimeVoiceInfosFieldNumber = 4;
    private static readonly pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo>.Codec _map_memRealTimeVoiceInfos_codec
        = new pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Zproto.TeamMemRealTimeVoiceInfo.Parser), 34);
    private readonly pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo> memRealTimeVoiceInfos_ = new pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo> MemRealTimeVoiceInfos {
      get { return memRealTimeVoiceInfos_; }
    }

    /// <summary>Field number for the "mem_voice_id" field.</summary>
    public const int MemVoiceIdFieldNumber = 6;
    private static readonly pbc::MapField<long, int>.Codec _map_memVoiceId_codec
        = new pbc::MapField<long, int>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForInt32(16, 0), 50);
    private readonly pbc::MapField<long, int> memVoiceId_ = new pbc::MapField<long, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, int> MemVoiceId {
      get { return memVoiceId_; }
    }

    /// <summary>Field number for the "member_fast_sync_data" field.</summary>
    public const int MemberFastSyncDataFieldNumber = 7;
    private static readonly pbc::MapField<long, global::Zproto.TeamMemberFastSyncData>.Codec _map_memberFastSyncData_codec
        = new pbc::MapField<long, global::Zproto.TeamMemberFastSyncData>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Zproto.TeamMemberFastSyncData.Parser), 58);
    private readonly pbc::MapField<long, global::Zproto.TeamMemberFastSyncData> memberFastSyncData_ = new pbc::MapField<long, global::Zproto.TeamMemberFastSyncData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Zproto.TeamMemberFastSyncData> MemberFastSyncData {
      get { return memberFastSyncData_; }
    }

    /// <summary>Field number for the "err_code" field.</summary>
    public const int ErrCodeFieldNumber = 8;
    private global::Zproto.EErrorCode errCode_ = global::Zproto.EErrorCode.ErrSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetTeamInfoReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetTeamInfoReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BaseInfo, other.BaseInfo)) return false;
      if(!memberData_.Equals(other.memberData_)) return false;
      if (!object.Equals(TeamActivity, other.TeamActivity)) return false;
      if (!MemRealTimeVoiceInfos.Equals(other.MemRealTimeVoiceInfos)) return false;
      if (!MemVoiceId.Equals(other.MemVoiceId)) return false;
      if (!MemberFastSyncData.Equals(other.MemberFastSyncData)) return false;
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (baseInfo_ != null) hash ^= BaseInfo.GetHashCode();
      hash ^= memberData_.GetHashCode();
      if (teamActivity_ != null) hash ^= TeamActivity.GetHashCode();
      hash ^= MemRealTimeVoiceInfos.GetHashCode();
      hash ^= MemVoiceId.GetHashCode();
      hash ^= MemberFastSyncData.GetHashCode();
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (baseInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseInfo);
      }
      memberData_.WriteTo(output, _repeated_memberData_codec);
      if (teamActivity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TeamActivity);
      }
      memRealTimeVoiceInfos_.WriteTo(output, _map_memRealTimeVoiceInfos_codec);
      memVoiceId_.WriteTo(output, _map_memVoiceId_codec);
      memberFastSyncData_.WriteTo(output, _map_memberFastSyncData_codec);
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(64);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (baseInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseInfo);
      }
      memberData_.WriteTo(ref output, _repeated_memberData_codec);
      if (teamActivity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TeamActivity);
      }
      memRealTimeVoiceInfos_.WriteTo(ref output, _map_memRealTimeVoiceInfos_codec);
      memVoiceId_.WriteTo(ref output, _map_memVoiceId_codec);
      memberFastSyncData_.WriteTo(ref output, _map_memberFastSyncData_codec);
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(64);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (baseInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseInfo);
      }
      size += memberData_.CalculateSize(_repeated_memberData_codec);
      if (teamActivity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TeamActivity);
      }
      size += memRealTimeVoiceInfos_.CalculateSize(_map_memRealTimeVoiceInfos_codec);
      size += memVoiceId_.CalculateSize(_map_memVoiceId_codec);
      size += memberFastSyncData_.CalculateSize(_map_memberFastSyncData_codec);
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetTeamInfoReply other) {
      if (other == null) {
        return;
      }
      if (other.baseInfo_ != null) {
        if (baseInfo_ == null) {
          BaseInfo = new global::Zproto.TeamBaseInfo();
        }
        BaseInfo.MergeFrom(other.BaseInfo);
      }
      memberData_.Add(other.memberData_);
      if (other.teamActivity_ != null) {
        if (teamActivity_ == null) {
          TeamActivity = new global::Zproto.TeamActivity();
        }
        TeamActivity.MergeFrom(other.TeamActivity);
      }
      memRealTimeVoiceInfos_.MergeFrom(other.memRealTimeVoiceInfos_);
      memVoiceId_.MergeFrom(other.memVoiceId_);
      memberFastSyncData_.MergeFrom(other.memberFastSyncData_);
      if (other.ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (baseInfo_ == null) {
              BaseInfo = new global::Zproto.TeamBaseInfo();
            }
            input.ReadMessage(BaseInfo);
            break;
          }
          case 18: {
            memberData_.AddEntriesFrom(input, _repeated_memberData_codec);
            break;
          }
          case 26: {
            if (teamActivity_ == null) {
              TeamActivity = new global::Zproto.TeamActivity();
            }
            input.ReadMessage(TeamActivity);
            break;
          }
          case 34: {
            memRealTimeVoiceInfos_.AddEntriesFrom(input, _map_memRealTimeVoiceInfos_codec);
            break;
          }
          case 50: {
            memVoiceId_.AddEntriesFrom(input, _map_memVoiceId_codec);
            break;
          }
          case 58: {
            memberFastSyncData_.AddEntriesFrom(input, _map_memberFastSyncData_codec);
            break;
          }
          case 64: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (baseInfo_ == null) {
              BaseInfo = new global::Zproto.TeamBaseInfo();
            }
            input.ReadMessage(BaseInfo);
            break;
          }
          case 18: {
            memberData_.AddEntriesFrom(ref input, _repeated_memberData_codec);
            break;
          }
          case 26: {
            if (teamActivity_ == null) {
              TeamActivity = new global::Zproto.TeamActivity();
            }
            input.ReadMessage(TeamActivity);
            break;
          }
          case 34: {
            memRealTimeVoiceInfos_.AddEntriesFrom(ref input, _map_memRealTimeVoiceInfos_codec);
            break;
          }
          case 50: {
            memVoiceId_.AddEntriesFrom(ref input, _map_memVoiceId_codec);
            break;
          }
          case 58: {
            memberFastSyncData_.AddEntriesFrom(ref input, _map_memberFastSyncData_codec);
            break;
          }
          case 64: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
