// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_save_action_group_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_save_action_group_request.proto</summary>
  public static partial class StruSaveActionGroupRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_save_action_group_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruSaveActionGroupRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRzdHJ1X3NhdmVfYWN0aW9uX2dyb3VwX3JlcXVlc3QucHJvdG8SBnpwcm90",
            "bxohc3RydV9hY3Rpb25fZ3JvdXBfc2F2ZV9pbmZvLnByb3RvIm4KFlNhdmVB",
            "Y3Rpb25Hcm91cFJlcXVlc3QSFwoPYWN0aW9uX2dyb3VwX2lkGAEgASgFEjsK",
            "FmFjdGlvbl9ncm91cF9zYXZlX2luZm8YAiABKAsyGy56cHJvdG8uQWN0aW9u",
            "R3JvdXBTYXZlSW5mb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruActionGroupSaveInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.SaveActionGroupRequest), global::Zproto.SaveActionGroupRequest.Parser, new[]{ "ActionGroupId", "ActionGroupSaveInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SaveActionGroupRequest : pb::IMessage<SaveActionGroupRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SaveActionGroupRequest> _parser = new pb::MessageParser<SaveActionGroupRequest>(() => new SaveActionGroupRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SaveActionGroupRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruSaveActionGroupRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SaveActionGroupRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SaveActionGroupRequest(SaveActionGroupRequest other) : this() {
      actionGroupId_ = other.actionGroupId_;
      actionGroupSaveInfo_ = other.actionGroupSaveInfo_ != null ? other.actionGroupSaveInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SaveActionGroupRequest Clone() {
      return new SaveActionGroupRequest(this);
    }

    /// <summary>Field number for the "action_group_id" field.</summary>
    public const int ActionGroupIdFieldNumber = 1;
    private int actionGroupId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ActionGroupId {
      get { return actionGroupId_; }
      set {
        actionGroupId_ = value;
      }
    }

    /// <summary>Field number for the "action_group_save_info" field.</summary>
    public const int ActionGroupSaveInfoFieldNumber = 2;
    private global::Zproto.ActionGroupSaveInfo actionGroupSaveInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ActionGroupSaveInfo ActionGroupSaveInfo {
      get { return actionGroupSaveInfo_; }
      set {
        actionGroupSaveInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SaveActionGroupRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SaveActionGroupRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionGroupId != other.ActionGroupId) return false;
      if (!object.Equals(ActionGroupSaveInfo, other.ActionGroupSaveInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionGroupId != 0) hash ^= ActionGroupId.GetHashCode();
      if (actionGroupSaveInfo_ != null) hash ^= ActionGroupSaveInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActionGroupId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ActionGroupId);
      }
      if (actionGroupSaveInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ActionGroupSaveInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActionGroupId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ActionGroupId);
      }
      if (actionGroupSaveInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ActionGroupSaveInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ActionGroupId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActionGroupId);
      }
      if (actionGroupSaveInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ActionGroupSaveInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SaveActionGroupRequest other) {
      if (other == null) {
        return;
      }
      if (other.ActionGroupId != 0) {
        ActionGroupId = other.ActionGroupId;
      }
      if (other.actionGroupSaveInfo_ != null) {
        if (actionGroupSaveInfo_ == null) {
          ActionGroupSaveInfo = new global::Zproto.ActionGroupSaveInfo();
        }
        ActionGroupSaveInfo.MergeFrom(other.ActionGroupSaveInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionGroupId = input.ReadInt32();
            break;
          }
          case 18: {
            if (actionGroupSaveInfo_ == null) {
              ActionGroupSaveInfo = new global::Zproto.ActionGroupSaveInfo();
            }
            input.ReadMessage(ActionGroupSaveInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActionGroupId = input.ReadInt32();
            break;
          }
          case 18: {
            if (actionGroupSaveInfo_ == null) {
              ActionGroupSaveInfo = new global::Zproto.ActionGroupSaveInfo();
            }
            input.ReadMessage(ActionGroupSaveInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
