// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_place_holder_scene_position.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_place_holder_scene_position.proto</summary>
  public static partial class StruPlaceHolderScenePositionReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_place_holder_scene_position.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruPlaceHolderScenePositionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZzdHJ1X3BsYWNlX2hvbGRlcl9zY2VuZV9wb3NpdGlvbi5wcm90bxIGenBy",
            "b3RvIowBChhQbGFjZUhvbGRlclNjZW5lUG9zaXRpb24SEAoIc2NlbmVfaWQY",
            "ASABKAUSDwoHbGluZV9pZBgCIAEoBRIRCglwb3NpdGlvbngYAyABKAUSEQoJ",
            "cG9zaXRpb255GAQgASgFEhEKCXBvc2l0aW9uehgFIAEoBRIUCgxtYXBfbGF5",
            "ZXJfaWQYBiABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.PlaceHolderScenePosition), global::Zproto.PlaceHolderScenePosition.Parser, new[]{ "SceneId", "LineId", "Positionx", "Positiony", "Positionz", "MapLayerId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlaceHolderScenePosition : pb::IMessage<PlaceHolderScenePosition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlaceHolderScenePosition> _parser = new pb::MessageParser<PlaceHolderScenePosition>(() => new PlaceHolderScenePosition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlaceHolderScenePosition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruPlaceHolderScenePositionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaceHolderScenePosition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaceHolderScenePosition(PlaceHolderScenePosition other) : this() {
      sceneId_ = other.sceneId_;
      lineId_ = other.lineId_;
      positionx_ = other.positionx_;
      positiony_ = other.positiony_;
      positionz_ = other.positionz_;
      mapLayerId_ = other.mapLayerId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaceHolderScenePosition Clone() {
      return new PlaceHolderScenePosition(this);
    }

    /// <summary>Field number for the "scene_id" field.</summary>
    public const int SceneIdFieldNumber = 1;
    private int sceneId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneId {
      get { return sceneId_; }
      set {
        sceneId_ = value;
      }
    }

    /// <summary>Field number for the "line_id" field.</summary>
    public const int LineIdFieldNumber = 2;
    private int lineId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LineId {
      get { return lineId_; }
      set {
        lineId_ = value;
      }
    }

    /// <summary>Field number for the "positionx" field.</summary>
    public const int PositionxFieldNumber = 3;
    private int positionx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Positionx {
      get { return positionx_; }
      set {
        positionx_ = value;
      }
    }

    /// <summary>Field number for the "positiony" field.</summary>
    public const int PositionyFieldNumber = 4;
    private int positiony_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Positiony {
      get { return positiony_; }
      set {
        positiony_ = value;
      }
    }

    /// <summary>Field number for the "positionz" field.</summary>
    public const int PositionzFieldNumber = 5;
    private int positionz_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Positionz {
      get { return positionz_; }
      set {
        positionz_ = value;
      }
    }

    /// <summary>Field number for the "map_layer_id" field.</summary>
    public const int MapLayerIdFieldNumber = 6;
    private int mapLayerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MapLayerId {
      get { return mapLayerId_; }
      set {
        mapLayerId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlaceHolderScenePosition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlaceHolderScenePosition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SceneId != other.SceneId) return false;
      if (LineId != other.LineId) return false;
      if (Positionx != other.Positionx) return false;
      if (Positiony != other.Positiony) return false;
      if (Positionz != other.Positionz) return false;
      if (MapLayerId != other.MapLayerId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SceneId != 0) hash ^= SceneId.GetHashCode();
      if (LineId != 0) hash ^= LineId.GetHashCode();
      if (Positionx != 0) hash ^= Positionx.GetHashCode();
      if (Positiony != 0) hash ^= Positiony.GetHashCode();
      if (Positionz != 0) hash ^= Positionz.GetHashCode();
      if (MapLayerId != 0) hash ^= MapLayerId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SceneId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SceneId);
      }
      if (LineId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LineId);
      }
      if (Positionx != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Positionx);
      }
      if (Positiony != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Positiony);
      }
      if (Positionz != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Positionz);
      }
      if (MapLayerId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MapLayerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SceneId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SceneId);
      }
      if (LineId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LineId);
      }
      if (Positionx != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Positionx);
      }
      if (Positiony != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Positiony);
      }
      if (Positionz != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Positionz);
      }
      if (MapLayerId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MapLayerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SceneId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneId);
      }
      if (LineId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LineId);
      }
      if (Positionx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Positionx);
      }
      if (Positiony != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Positiony);
      }
      if (Positionz != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Positionz);
      }
      if (MapLayerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MapLayerId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlaceHolderScenePosition other) {
      if (other == null) {
        return;
      }
      if (other.SceneId != 0) {
        SceneId = other.SceneId;
      }
      if (other.LineId != 0) {
        LineId = other.LineId;
      }
      if (other.Positionx != 0) {
        Positionx = other.Positionx;
      }
      if (other.Positiony != 0) {
        Positiony = other.Positiony;
      }
      if (other.Positionz != 0) {
        Positionz = other.Positionz;
      }
      if (other.MapLayerId != 0) {
        MapLayerId = other.MapLayerId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SceneId = input.ReadInt32();
            break;
          }
          case 16: {
            LineId = input.ReadInt32();
            break;
          }
          case 24: {
            Positionx = input.ReadInt32();
            break;
          }
          case 32: {
            Positiony = input.ReadInt32();
            break;
          }
          case 40: {
            Positionz = input.ReadInt32();
            break;
          }
          case 48: {
            MapLayerId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SceneId = input.ReadInt32();
            break;
          }
          case 16: {
            LineId = input.ReadInt32();
            break;
          }
          case 24: {
            Positionx = input.ReadInt32();
            break;
          }
          case 32: {
            Positiony = input.ReadInt32();
            break;
          }
          case 40: {
            Positionz = input.ReadInt32();
            break;
          }
          case 48: {
            MapLayerId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
