// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_homeland_base_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_homeland_base_info.proto</summary>
  public static partial class StruHomelandBaseInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_homeland_base_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruHomelandBaseInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1zdHJ1X2hvbWVsYW5kX2Jhc2VfaW5mby5wcm90bxIGenByb3RvGh1zdHJ1",
            "X2NvbW11bml0eV90cmFuc2Zlci5wcm90bxouc3RydV9ob21lX2xhbmRfY2x1",
            "dHRlcl9nZW5lcmF0aW9uX3JlY29yZC5wcm90bxohc3RydV9ob21lX2xhbmRf",
            "Y2x1dHRlcl9pbmZvLnByb3RvGiJzdHJ1X2hvbWVfbGFuZF9pdGVtX2luc3Rh",
            "bmNlLnByb3RvGiNzdHJ1X2hvbWVfbGFuZF9zZWxsX3Nob3BfaW5mby5wcm90",
            "bxoec3RydV9ob21lbGFuZF92aXNpdF9pbmZvLnByb3RvIqQGChBIb21lbGFu",
            "ZEJhc2VJbmZvEi0KCnZpc2l0X2luZm8YASABKAsyGS56cHJvdG8uSG9tZWxh",
            "bmRWaXNpdEluZm8SCwoDZXhwGAIgASgDEhUKDWhvbWVfcmVzb3VyY2UYAyAB",
            "KAMSIwobbGFzdHN1YnRyYWN0Y2xlYW5saW5lc3N0aW1lGAQgASgDEjYKEWhv",
            "bWVfbGFuZF9jbHV0dGVyGAUgASgLMhsuenByb3RvLkhvbWVMYW5kQ2x1dHRl",
            "ckluZm8SVAojaG9tZV9sYW5kX2NsdXR0ZXJfZ2VuZXJhdGlvbl9yZWNvcmQY",
            "BiABKAsyJy56cHJvdG8uSG9tZUxhbmRDbHV0dGVyR2VuZXJhdGlvblJlY29y",
            "ZBI+Chhob21lX2xhbmRfc2VsbF9zaG9wX2luZm8YByABKAsyHC56cHJvdG8u",
            "SG9tZUxhbmRTZWxsU2hvcEluZm8SMgoFaXRlbXMYCCADKAsyIy56cHJvdG8u",
            "SG9tZWxhbmRCYXNlSW5mby5JdGVtc0VudHJ5EjIKBXNsb3RzGAkgAygLMiMu",
            "enByb3RvLkhvbWVsYW5kQmFzZUluZm8uU2xvdHNFbnRyeRI+CgxpdGVtX3Rv",
            "X3Nsb3QYCiADKAsyKC56cHJvdG8uSG9tZWxhbmRCYXNlSW5mby5JdGVtVG9T",
            "bG90RW50cnkSEAoIY2FwYWNpdHkYCyABKAMSEgoKdXNlZF9zbG90cxgMIAEo",
            "AxIYChBjaGVja19pbl9jb250ZW50GA0gASgJEjUKEnRyYW5zZmVyX2NvbW11",
            "bml0eRgOIAEoCzIZLnpwcm90by5Db21tdW5pdHlUcmFuc2ZlchpKCgpJdGVt",
            "c0VudHJ5EgsKA2tleRgBIAEoAxIrCgV2YWx1ZRgCIAEoCzIcLnpwcm90by5I",
            "b21lTGFuZEl0ZW1JbnN0YW5jZToCOAEaLAoKU2xvdHNFbnRyeRILCgNrZXkY",
            "ASABKAMSDQoFdmFsdWUYAiABKAM6AjgBGjEKD0l0ZW1Ub1Nsb3RFbnRyeRIL",
            "CgNrZXkYASABKAMSDQoFdmFsdWUYAiABKAM6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruCommunityTransferReflection.Descriptor, global::Zproto.StruHomeLandClutterGenerationRecordReflection.Descriptor, global::Zproto.StruHomeLandClutterInfoReflection.Descriptor, global::Zproto.StruHomeLandItemInstanceReflection.Descriptor, global::Zproto.StruHomeLandSellShopInfoReflection.Descriptor, global::Zproto.StruHomelandVisitInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.HomelandBaseInfo), global::Zproto.HomelandBaseInfo.Parser, new[]{ "VisitInfo", "Exp", "HomeResource", "Lastsubtractcleanlinesstime", "HomeLandClutter", "HomeLandClutterGenerationRecord", "HomeLandSellShopInfo", "Items", "Slots", "ItemToSlot", "Capacity", "UsedSlots", "CheckInContent", "TransferCommunity" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HomelandBaseInfo : pb::IMessage<HomelandBaseInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HomelandBaseInfo> _parser = new pb::MessageParser<HomelandBaseInfo>(() => new HomelandBaseInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HomelandBaseInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruHomelandBaseInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandBaseInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandBaseInfo(HomelandBaseInfo other) : this() {
      visitInfo_ = other.visitInfo_ != null ? other.visitInfo_.Clone() : null;
      exp_ = other.exp_;
      homeResource_ = other.homeResource_;
      lastsubtractcleanlinesstime_ = other.lastsubtractcleanlinesstime_;
      homeLandClutter_ = other.homeLandClutter_ != null ? other.homeLandClutter_.Clone() : null;
      homeLandClutterGenerationRecord_ = other.homeLandClutterGenerationRecord_ != null ? other.homeLandClutterGenerationRecord_.Clone() : null;
      homeLandSellShopInfo_ = other.homeLandSellShopInfo_ != null ? other.homeLandSellShopInfo_.Clone() : null;
      items_ = other.items_.Clone();
      slots_ = other.slots_.Clone();
      itemToSlot_ = other.itemToSlot_.Clone();
      capacity_ = other.capacity_;
      usedSlots_ = other.usedSlots_;
      checkInContent_ = other.checkInContent_;
      transferCommunity_ = other.transferCommunity_ != null ? other.transferCommunity_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandBaseInfo Clone() {
      return new HomelandBaseInfo(this);
    }

    /// <summary>Field number for the "visit_info" field.</summary>
    public const int VisitInfoFieldNumber = 1;
    private global::Zproto.HomelandVisitInfo visitInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.HomelandVisitInfo VisitInfo {
      get { return visitInfo_; }
      set {
        visitInfo_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 2;
    private long exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "home_resource" field.</summary>
    public const int HomeResourceFieldNumber = 3;
    private long homeResource_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HomeResource {
      get { return homeResource_; }
      set {
        homeResource_ = value;
      }
    }

    /// <summary>Field number for the "lastsubtractcleanlinesstime" field.</summary>
    public const int LastsubtractcleanlinesstimeFieldNumber = 4;
    private long lastsubtractcleanlinesstime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Lastsubtractcleanlinesstime {
      get { return lastsubtractcleanlinesstime_; }
      set {
        lastsubtractcleanlinesstime_ = value;
      }
    }

    /// <summary>Field number for the "home_land_clutter" field.</summary>
    public const int HomeLandClutterFieldNumber = 5;
    private global::Zproto.HomeLandClutterInfo homeLandClutter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.HomeLandClutterInfo HomeLandClutter {
      get { return homeLandClutter_; }
      set {
        homeLandClutter_ = value;
      }
    }

    /// <summary>Field number for the "home_land_clutter_generation_record" field.</summary>
    public const int HomeLandClutterGenerationRecordFieldNumber = 6;
    private global::Zproto.HomeLandClutterGenerationRecord homeLandClutterGenerationRecord_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.HomeLandClutterGenerationRecord HomeLandClutterGenerationRecord {
      get { return homeLandClutterGenerationRecord_; }
      set {
        homeLandClutterGenerationRecord_ = value;
      }
    }

    /// <summary>Field number for the "home_land_sell_shop_info" field.</summary>
    public const int HomeLandSellShopInfoFieldNumber = 7;
    private global::Zproto.HomeLandSellShopInfo homeLandSellShopInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.HomeLandSellShopInfo HomeLandSellShopInfo {
      get { return homeLandSellShopInfo_; }
      set {
        homeLandSellShopInfo_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 8;
    private static readonly pbc::MapField<long, global::Zproto.HomeLandItemInstance>.Codec _map_items_codec
        = new pbc::MapField<long, global::Zproto.HomeLandItemInstance>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Zproto.HomeLandItemInstance.Parser), 66);
    private readonly pbc::MapField<long, global::Zproto.HomeLandItemInstance> items_ = new pbc::MapField<long, global::Zproto.HomeLandItemInstance>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Zproto.HomeLandItemInstance> Items {
      get { return items_; }
    }

    /// <summary>Field number for the "slots" field.</summary>
    public const int SlotsFieldNumber = 9;
    private static readonly pbc::MapField<long, long>.Codec _map_slots_codec
        = new pbc::MapField<long, long>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForInt64(16, 0L), 74);
    private readonly pbc::MapField<long, long> slots_ = new pbc::MapField<long, long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, long> Slots {
      get { return slots_; }
    }

    /// <summary>Field number for the "item_to_slot" field.</summary>
    public const int ItemToSlotFieldNumber = 10;
    private static readonly pbc::MapField<long, long>.Codec _map_itemToSlot_codec
        = new pbc::MapField<long, long>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForInt64(16, 0L), 82);
    private readonly pbc::MapField<long, long> itemToSlot_ = new pbc::MapField<long, long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, long> ItemToSlot {
      get { return itemToSlot_; }
    }

    /// <summary>Field number for the "capacity" field.</summary>
    public const int CapacityFieldNumber = 11;
    private long capacity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Capacity {
      get { return capacity_; }
      set {
        capacity_ = value;
      }
    }

    /// <summary>Field number for the "used_slots" field.</summary>
    public const int UsedSlotsFieldNumber = 12;
    private long usedSlots_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UsedSlots {
      get { return usedSlots_; }
      set {
        usedSlots_ = value;
      }
    }

    /// <summary>Field number for the "check_in_content" field.</summary>
    public const int CheckInContentFieldNumber = 13;
    private string checkInContent_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CheckInContent {
      get { return checkInContent_; }
      set {
        checkInContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "transfer_community" field.</summary>
    public const int TransferCommunityFieldNumber = 14;
    private global::Zproto.CommunityTransfer transferCommunity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.CommunityTransfer TransferCommunity {
      get { return transferCommunity_; }
      set {
        transferCommunity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HomelandBaseInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HomelandBaseInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VisitInfo, other.VisitInfo)) return false;
      if (Exp != other.Exp) return false;
      if (HomeResource != other.HomeResource) return false;
      if (Lastsubtractcleanlinesstime != other.Lastsubtractcleanlinesstime) return false;
      if (!object.Equals(HomeLandClutter, other.HomeLandClutter)) return false;
      if (!object.Equals(HomeLandClutterGenerationRecord, other.HomeLandClutterGenerationRecord)) return false;
      if (!object.Equals(HomeLandSellShopInfo, other.HomeLandSellShopInfo)) return false;
      if (!Items.Equals(other.Items)) return false;
      if (!Slots.Equals(other.Slots)) return false;
      if (!ItemToSlot.Equals(other.ItemToSlot)) return false;
      if (Capacity != other.Capacity) return false;
      if (UsedSlots != other.UsedSlots) return false;
      if (CheckInContent != other.CheckInContent) return false;
      if (!object.Equals(TransferCommunity, other.TransferCommunity)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (visitInfo_ != null) hash ^= VisitInfo.GetHashCode();
      if (Exp != 0L) hash ^= Exp.GetHashCode();
      if (HomeResource != 0L) hash ^= HomeResource.GetHashCode();
      if (Lastsubtractcleanlinesstime != 0L) hash ^= Lastsubtractcleanlinesstime.GetHashCode();
      if (homeLandClutter_ != null) hash ^= HomeLandClutter.GetHashCode();
      if (homeLandClutterGenerationRecord_ != null) hash ^= HomeLandClutterGenerationRecord.GetHashCode();
      if (homeLandSellShopInfo_ != null) hash ^= HomeLandSellShopInfo.GetHashCode();
      hash ^= Items.GetHashCode();
      hash ^= Slots.GetHashCode();
      hash ^= ItemToSlot.GetHashCode();
      if (Capacity != 0L) hash ^= Capacity.GetHashCode();
      if (UsedSlots != 0L) hash ^= UsedSlots.GetHashCode();
      if (CheckInContent.Length != 0) hash ^= CheckInContent.GetHashCode();
      if (transferCommunity_ != null) hash ^= TransferCommunity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (visitInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VisitInfo);
      }
      if (Exp != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Exp);
      }
      if (HomeResource != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(HomeResource);
      }
      if (Lastsubtractcleanlinesstime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Lastsubtractcleanlinesstime);
      }
      if (homeLandClutter_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(HomeLandClutter);
      }
      if (homeLandClutterGenerationRecord_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(HomeLandClutterGenerationRecord);
      }
      if (homeLandSellShopInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(HomeLandSellShopInfo);
      }
      items_.WriteTo(output, _map_items_codec);
      slots_.WriteTo(output, _map_slots_codec);
      itemToSlot_.WriteTo(output, _map_itemToSlot_codec);
      if (Capacity != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Capacity);
      }
      if (UsedSlots != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(UsedSlots);
      }
      if (CheckInContent.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(CheckInContent);
      }
      if (transferCommunity_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(TransferCommunity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (visitInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(VisitInfo);
      }
      if (Exp != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Exp);
      }
      if (HomeResource != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(HomeResource);
      }
      if (Lastsubtractcleanlinesstime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Lastsubtractcleanlinesstime);
      }
      if (homeLandClutter_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(HomeLandClutter);
      }
      if (homeLandClutterGenerationRecord_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(HomeLandClutterGenerationRecord);
      }
      if (homeLandSellShopInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(HomeLandSellShopInfo);
      }
      items_.WriteTo(ref output, _map_items_codec);
      slots_.WriteTo(ref output, _map_slots_codec);
      itemToSlot_.WriteTo(ref output, _map_itemToSlot_codec);
      if (Capacity != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Capacity);
      }
      if (UsedSlots != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(UsedSlots);
      }
      if (CheckInContent.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(CheckInContent);
      }
      if (transferCommunity_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(TransferCommunity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (visitInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VisitInfo);
      }
      if (Exp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Exp);
      }
      if (HomeResource != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(HomeResource);
      }
      if (Lastsubtractcleanlinesstime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Lastsubtractcleanlinesstime);
      }
      if (homeLandClutter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HomeLandClutter);
      }
      if (homeLandClutterGenerationRecord_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HomeLandClutterGenerationRecord);
      }
      if (homeLandSellShopInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HomeLandSellShopInfo);
      }
      size += items_.CalculateSize(_map_items_codec);
      size += slots_.CalculateSize(_map_slots_codec);
      size += itemToSlot_.CalculateSize(_map_itemToSlot_codec);
      if (Capacity != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Capacity);
      }
      if (UsedSlots != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UsedSlots);
      }
      if (CheckInContent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CheckInContent);
      }
      if (transferCommunity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TransferCommunity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HomelandBaseInfo other) {
      if (other == null) {
        return;
      }
      if (other.visitInfo_ != null) {
        if (visitInfo_ == null) {
          VisitInfo = new global::Zproto.HomelandVisitInfo();
        }
        VisitInfo.MergeFrom(other.VisitInfo);
      }
      if (other.Exp != 0L) {
        Exp = other.Exp;
      }
      if (other.HomeResource != 0L) {
        HomeResource = other.HomeResource;
      }
      if (other.Lastsubtractcleanlinesstime != 0L) {
        Lastsubtractcleanlinesstime = other.Lastsubtractcleanlinesstime;
      }
      if (other.homeLandClutter_ != null) {
        if (homeLandClutter_ == null) {
          HomeLandClutter = new global::Zproto.HomeLandClutterInfo();
        }
        HomeLandClutter.MergeFrom(other.HomeLandClutter);
      }
      if (other.homeLandClutterGenerationRecord_ != null) {
        if (homeLandClutterGenerationRecord_ == null) {
          HomeLandClutterGenerationRecord = new global::Zproto.HomeLandClutterGenerationRecord();
        }
        HomeLandClutterGenerationRecord.MergeFrom(other.HomeLandClutterGenerationRecord);
      }
      if (other.homeLandSellShopInfo_ != null) {
        if (homeLandSellShopInfo_ == null) {
          HomeLandSellShopInfo = new global::Zproto.HomeLandSellShopInfo();
        }
        HomeLandSellShopInfo.MergeFrom(other.HomeLandSellShopInfo);
      }
      items_.MergeFrom(other.items_);
      slots_.MergeFrom(other.slots_);
      itemToSlot_.MergeFrom(other.itemToSlot_);
      if (other.Capacity != 0L) {
        Capacity = other.Capacity;
      }
      if (other.UsedSlots != 0L) {
        UsedSlots = other.UsedSlots;
      }
      if (other.CheckInContent.Length != 0) {
        CheckInContent = other.CheckInContent;
      }
      if (other.transferCommunity_ != null) {
        if (transferCommunity_ == null) {
          TransferCommunity = new global::Zproto.CommunityTransfer();
        }
        TransferCommunity.MergeFrom(other.TransferCommunity);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (visitInfo_ == null) {
              VisitInfo = new global::Zproto.HomelandVisitInfo();
            }
            input.ReadMessage(VisitInfo);
            break;
          }
          case 16: {
            Exp = input.ReadInt64();
            break;
          }
          case 24: {
            HomeResource = input.ReadInt64();
            break;
          }
          case 32: {
            Lastsubtractcleanlinesstime = input.ReadInt64();
            break;
          }
          case 42: {
            if (homeLandClutter_ == null) {
              HomeLandClutter = new global::Zproto.HomeLandClutterInfo();
            }
            input.ReadMessage(HomeLandClutter);
            break;
          }
          case 50: {
            if (homeLandClutterGenerationRecord_ == null) {
              HomeLandClutterGenerationRecord = new global::Zproto.HomeLandClutterGenerationRecord();
            }
            input.ReadMessage(HomeLandClutterGenerationRecord);
            break;
          }
          case 58: {
            if (homeLandSellShopInfo_ == null) {
              HomeLandSellShopInfo = new global::Zproto.HomeLandSellShopInfo();
            }
            input.ReadMessage(HomeLandSellShopInfo);
            break;
          }
          case 66: {
            items_.AddEntriesFrom(input, _map_items_codec);
            break;
          }
          case 74: {
            slots_.AddEntriesFrom(input, _map_slots_codec);
            break;
          }
          case 82: {
            itemToSlot_.AddEntriesFrom(input, _map_itemToSlot_codec);
            break;
          }
          case 88: {
            Capacity = input.ReadInt64();
            break;
          }
          case 96: {
            UsedSlots = input.ReadInt64();
            break;
          }
          case 106: {
            CheckInContent = input.ReadString();
            break;
          }
          case 114: {
            if (transferCommunity_ == null) {
              TransferCommunity = new global::Zproto.CommunityTransfer();
            }
            input.ReadMessage(TransferCommunity);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (visitInfo_ == null) {
              VisitInfo = new global::Zproto.HomelandVisitInfo();
            }
            input.ReadMessage(VisitInfo);
            break;
          }
          case 16: {
            Exp = input.ReadInt64();
            break;
          }
          case 24: {
            HomeResource = input.ReadInt64();
            break;
          }
          case 32: {
            Lastsubtractcleanlinesstime = input.ReadInt64();
            break;
          }
          case 42: {
            if (homeLandClutter_ == null) {
              HomeLandClutter = new global::Zproto.HomeLandClutterInfo();
            }
            input.ReadMessage(HomeLandClutter);
            break;
          }
          case 50: {
            if (homeLandClutterGenerationRecord_ == null) {
              HomeLandClutterGenerationRecord = new global::Zproto.HomeLandClutterGenerationRecord();
            }
            input.ReadMessage(HomeLandClutterGenerationRecord);
            break;
          }
          case 58: {
            if (homeLandSellShopInfo_ == null) {
              HomeLandSellShopInfo = new global::Zproto.HomeLandSellShopInfo();
            }
            input.ReadMessage(HomeLandSellShopInfo);
            break;
          }
          case 66: {
            items_.AddEntriesFrom(ref input, _map_items_codec);
            break;
          }
          case 74: {
            slots_.AddEntriesFrom(ref input, _map_slots_codec);
            break;
          }
          case 82: {
            itemToSlot_.AddEntriesFrom(ref input, _map_itemToSlot_codec);
            break;
          }
          case 88: {
            Capacity = input.ReadInt64();
            break;
          }
          case 96: {
            UsedSlots = input.ReadInt64();
            break;
          }
          case 106: {
            CheckInContent = input.ReadString();
            break;
          }
          case 114: {
            if (transferCommunity_ == null) {
              TransferCommunity = new global::Zproto.CommunityTransfer();
            }
            input.ReadMessage(TransferCommunity);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
