// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_mahjong_settle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_mahjong_settle.proto</summary>
  public static partial class StruMahjongSettleReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_mahjong_settle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruMahjongSettleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlzdHJ1X21haGpvbmdfc2V0dGxlLnByb3RvEgZ6cHJvdG8aHmVudW1fbWFo",
            "am9uZ19zZXR0bGVfdHlwZS5wcm90byKLAQoNTWFoam9uZ1NldHRsZRIuCgtz",
            "ZXR0bGVfdHlwZRgBIAEoDjIZLnpwcm90by5NYWhqb25nU2V0dGxlVHlwZRIR",
            "CglwbGF5ZXJfaWQYAiABKAMSCgoCeWkYAyABKAUSCwoDaGFuGAQgASgFEg0K",
            "BWZ1c2h1GAUgASgFEg8KB3NlY29uZHMYBiABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumMahjongSettleTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.MahjongSettle), global::Zproto.MahjongSettle.Parser, new[]{ "SettleType", "PlayerId", "Yi", "Han", "Fushu", "Seconds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MahjongSettle : pb::IMessage<MahjongSettle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MahjongSettle> _parser = new pb::MessageParser<MahjongSettle>(() => new MahjongSettle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MahjongSettle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruMahjongSettleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MahjongSettle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MahjongSettle(MahjongSettle other) : this() {
      settleType_ = other.settleType_;
      playerId_ = other.playerId_;
      yi_ = other.yi_;
      han_ = other.han_;
      fushu_ = other.fushu_;
      seconds_ = other.seconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MahjongSettle Clone() {
      return new MahjongSettle(this);
    }

    /// <summary>Field number for the "settle_type" field.</summary>
    public const int SettleTypeFieldNumber = 1;
    private global::Zproto.MahjongSettleType settleType_ = global::Zproto.MahjongSettleType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.MahjongSettleType SettleType {
      get { return settleType_; }
      set {
        settleType_ = value;
      }
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 2;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "yi" field.</summary>
    public const int YiFieldNumber = 3;
    private int yi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Yi {
      get { return yi_; }
      set {
        yi_ = value;
      }
    }

    /// <summary>Field number for the "han" field.</summary>
    public const int HanFieldNumber = 4;
    private int han_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Han {
      get { return han_; }
      set {
        han_ = value;
      }
    }

    /// <summary>Field number for the "fushu" field.</summary>
    public const int FushuFieldNumber = 5;
    private int fushu_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Fushu {
      get { return fushu_; }
      set {
        fushu_ = value;
      }
    }

    /// <summary>Field number for the "seconds" field.</summary>
    public const int SecondsFieldNumber = 6;
    private int seconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Seconds {
      get { return seconds_; }
      set {
        seconds_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MahjongSettle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MahjongSettle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SettleType != other.SettleType) return false;
      if (PlayerId != other.PlayerId) return false;
      if (Yi != other.Yi) return false;
      if (Han != other.Han) return false;
      if (Fushu != other.Fushu) return false;
      if (Seconds != other.Seconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SettleType != global::Zproto.MahjongSettleType.None) hash ^= SettleType.GetHashCode();
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (Yi != 0) hash ^= Yi.GetHashCode();
      if (Han != 0) hash ^= Han.GetHashCode();
      if (Fushu != 0) hash ^= Fushu.GetHashCode();
      if (Seconds != 0) hash ^= Seconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SettleType != global::Zproto.MahjongSettleType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) SettleType);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (Yi != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Yi);
      }
      if (Han != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Han);
      }
      if (Fushu != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Fushu);
      }
      if (Seconds != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Seconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SettleType != global::Zproto.MahjongSettleType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) SettleType);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (Yi != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Yi);
      }
      if (Han != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Han);
      }
      if (Fushu != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Fushu);
      }
      if (Seconds != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Seconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SettleType != global::Zproto.MahjongSettleType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SettleType);
      }
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (Yi != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Yi);
      }
      if (Han != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Han);
      }
      if (Fushu != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Fushu);
      }
      if (Seconds != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seconds);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MahjongSettle other) {
      if (other == null) {
        return;
      }
      if (other.SettleType != global::Zproto.MahjongSettleType.None) {
        SettleType = other.SettleType;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.Yi != 0) {
        Yi = other.Yi;
      }
      if (other.Han != 0) {
        Han = other.Han;
      }
      if (other.Fushu != 0) {
        Fushu = other.Fushu;
      }
      if (other.Seconds != 0) {
        Seconds = other.Seconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SettleType = (global::Zproto.MahjongSettleType) input.ReadEnum();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            Yi = input.ReadInt32();
            break;
          }
          case 32: {
            Han = input.ReadInt32();
            break;
          }
          case 40: {
            Fushu = input.ReadInt32();
            break;
          }
          case 48: {
            Seconds = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SettleType = (global::Zproto.MahjongSettleType) input.ReadEnum();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            Yi = input.ReadInt32();
            break;
          }
          case 32: {
            Han = input.ReadInt32();
            break;
          }
          case 40: {
            Fushu = input.ReadInt32();
            break;
          }
          case 48: {
            Seconds = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
