// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_project_extra_sync_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_project_extra_sync_data.proto</summary>
  public static partial class StruProjectExtraSyncDataReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_project_extra_sync_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruProjectExtraSyncDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJzdHJ1X3Byb2plY3RfZXh0cmFfc3luY19kYXRhLnByb3RvEgZ6cHJvdG8a",
            "IXN0cnVfcHJvZmVzc2lvbl90YWxlbnRfaW5mby5wcm90byLkAQoUUHJvamVj",
            "dEV4dHJhU3luY0RhdGESPAoWY3VycmVudF90YWxlbnRfaWRfbGlzdBgBIAEo",
            "CzIcLnpwcm90by5Qcm9mZXNzaW9uVGFsZW50SW5mbxJTChVjdXJyZW50X3Nr",
            "aWxsX2lkX2xpc3QYAiADKAsyNC56cHJvdG8uUHJvamVjdEV4dHJhU3luY0Rh",
            "dGEuQ3VycmVudFNraWxsSWRMaXN0RW50cnkaOQoXQ3VycmVudFNraWxsSWRM",
            "aXN0RW50cnkSCwoDa2V5GAEgASgFEg0KBXZhbHVlGAIgASgFOgI4AWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruProfessionTalentInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.ProjectExtraSyncData), global::Zproto.ProjectExtraSyncData.Parser, new[]{ "CurrentTalentIdList", "CurrentSkillIdList" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProjectExtraSyncData : pb::IMessage<ProjectExtraSyncData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProjectExtraSyncData> _parser = new pb::MessageParser<ProjectExtraSyncData>(() => new ProjectExtraSyncData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProjectExtraSyncData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruProjectExtraSyncDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectExtraSyncData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectExtraSyncData(ProjectExtraSyncData other) : this() {
      currentTalentIdList_ = other.currentTalentIdList_ != null ? other.currentTalentIdList_.Clone() : null;
      currentSkillIdList_ = other.currentSkillIdList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectExtraSyncData Clone() {
      return new ProjectExtraSyncData(this);
    }

    /// <summary>Field number for the "current_talent_id_list" field.</summary>
    public const int CurrentTalentIdListFieldNumber = 1;
    private global::Zproto.ProfessionTalentInfo currentTalentIdList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ProfessionTalentInfo CurrentTalentIdList {
      get { return currentTalentIdList_; }
      set {
        currentTalentIdList_ = value;
      }
    }

    /// <summary>Field number for the "current_skill_id_list" field.</summary>
    public const int CurrentSkillIdListFieldNumber = 2;
    private static readonly pbc::MapField<int, int>.Codec _map_currentSkillIdList_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 18);
    private readonly pbc::MapField<int, int> currentSkillIdList_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> CurrentSkillIdList {
      get { return currentSkillIdList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProjectExtraSyncData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProjectExtraSyncData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CurrentTalentIdList, other.CurrentTalentIdList)) return false;
      if (!CurrentSkillIdList.Equals(other.CurrentSkillIdList)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (currentTalentIdList_ != null) hash ^= CurrentTalentIdList.GetHashCode();
      hash ^= CurrentSkillIdList.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (currentTalentIdList_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrentTalentIdList);
      }
      currentSkillIdList_.WriteTo(output, _map_currentSkillIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (currentTalentIdList_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrentTalentIdList);
      }
      currentSkillIdList_.WriteTo(ref output, _map_currentSkillIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (currentTalentIdList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentTalentIdList);
      }
      size += currentSkillIdList_.CalculateSize(_map_currentSkillIdList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProjectExtraSyncData other) {
      if (other == null) {
        return;
      }
      if (other.currentTalentIdList_ != null) {
        if (currentTalentIdList_ == null) {
          CurrentTalentIdList = new global::Zproto.ProfessionTalentInfo();
        }
        CurrentTalentIdList.MergeFrom(other.CurrentTalentIdList);
      }
      currentSkillIdList_.MergeFrom(other.currentSkillIdList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (currentTalentIdList_ == null) {
              CurrentTalentIdList = new global::Zproto.ProfessionTalentInfo();
            }
            input.ReadMessage(CurrentTalentIdList);
            break;
          }
          case 18: {
            currentSkillIdList_.AddEntriesFrom(input, _map_currentSkillIdList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (currentTalentIdList_ == null) {
              CurrentTalentIdList = new global::Zproto.ProfessionTalentInfo();
            }
            input.ReadMessage(CurrentTalentIdList);
            break;
          }
          case 18: {
            currentSkillIdList_.AddEntriesFrom(ref input, _map_currentSkillIdList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
