// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_reputation_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_reputation_info.proto</summary>
  public static partial class StruReputationInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_reputation_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruReputationInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpzdHJ1X3JlcHV0YXRpb25faW5mby5wcm90bxIGenByb3RvGhVzdHJ1X2Rp",
            "cnR5X21hc2sucHJvdG8irAEKDlJlcHV0YXRpb25JbmZvEhYKDnJlcHV0YXRp",
            "b25fZXhwGAEgASgEEhgKEHJlcHV0YXRpb25fbGV2ZWwYAiABKAUSNwoJYXdh",
            "cmRfbWFwGAMgAygLMiQuenByb3RvLlJlcHV0YXRpb25JbmZvLkF3YXJkTWFw",
            "RW50cnkaLwoNQXdhcmRNYXBFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUY",
            "AiABKAg6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.ReputationInfo), global::Zproto.ReputationInfo.Parser, new[]{ "ReputationExp", "ReputationLevel", "AwardMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ReputationInfo : pb::IMessage<ReputationInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReputationInfo> _parser = new pb::MessageParser<ReputationInfo>(() => new ReputationInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReputationInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruReputationInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReputationInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReputationInfo(ReputationInfo other) : this() {
      reputationExp_ = other.reputationExp_;
      reputationLevel_ = other.reputationLevel_;
      awardMap_ = other.awardMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReputationInfo Clone() {
      return new ReputationInfo(this);
    }

    /// <summary>Field number for the "reputation_exp" field.</summary>
    public const int ReputationExpFieldNumber = 1;
    private ulong reputationExp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ReputationExp {
      get { return reputationExp_; }
      set {
        reputationExp_ = value;
      }
    }

    /// <summary>Field number for the "reputation_level" field.</summary>
    public const int ReputationLevelFieldNumber = 2;
    private int reputationLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReputationLevel {
      get { return reputationLevel_; }
      set {
        reputationLevel_ = value;
      }
    }

    /// <summary>Field number for the "award_map" field.</summary>
    public const int AwardMapFieldNumber = 3;
    private static readonly pbc::MapField<int, bool>.Codec _map_awardMap_codec
        = new pbc::MapField<int, bool>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBool(16, false), 26);
    private readonly pbc::MapField<int, bool> awardMap_ = new pbc::MapField<int, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, bool> AwardMap {
      get { return awardMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReputationInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReputationInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReputationExp != other.ReputationExp) return false;
      if (ReputationLevel != other.ReputationLevel) return false;
      if (!AwardMap.Equals(other.AwardMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ReputationExp != 0UL) hash ^= ReputationExp.GetHashCode();
      if (ReputationLevel != 0) hash ^= ReputationLevel.GetHashCode();
      hash ^= AwardMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ReputationExp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ReputationExp);
      }
      if (ReputationLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ReputationLevel);
      }
      awardMap_.WriteTo(output, _map_awardMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ReputationExp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ReputationExp);
      }
      if (ReputationLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ReputationLevel);
      }
      awardMap_.WriteTo(ref output, _map_awardMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ReputationExp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ReputationExp);
      }
      if (ReputationLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReputationLevel);
      }
      size += awardMap_.CalculateSize(_map_awardMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReputationInfo other) {
      if (other == null) {
        return;
      }
      if (other.ReputationExp != 0UL) {
        ReputationExp = other.ReputationExp;
      }
      if (other.ReputationLevel != 0) {
        ReputationLevel = other.ReputationLevel;
      }
      awardMap_.MergeFrom(other.awardMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReputationExp = input.ReadUInt64();
            break;
          }
          case 16: {
            ReputationLevel = input.ReadInt32();
            break;
          }
          case 26: {
            awardMap_.AddEntriesFrom(input, _map_awardMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ReputationExp = input.ReadUInt64();
            break;
          }
          case 16: {
            ReputationLevel = input.ReadInt32();
            break;
          }
          case 26: {
            awardMap_.AddEntriesFrom(ref input, _map_awardMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
