// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_pay_order_list.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_pay_order_list.proto</summary>
  public static partial class StruPayOrderListReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_pay_order_list.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruPayOrderListReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlzdHJ1X3BheV9vcmRlcl9saXN0LnByb3RvEgZ6cHJvdG8aE3N0cnVfcGF5",
            "X2RhdGEucHJvdG8aG3N0cnVfcmVmdW5kX2l0ZW1faW5mby5wcm90bxoVc3Ry",
            "dV9kaXJ0eV9tYXNrLnByb3RvIoQDCgxQYXlPcmRlckxpc3QSFgoOcGF5X29y",
            "ZGVyX2xpc3QYASADKAkSFwoPcGF5X3JlZnVuZF9saXN0GAIgAygJEiIKCWZp",
            "cnN0X3BheRgDIAEoCzIPLnpwcm90by5QYXlEYXRhEkIKEG9yZGVyX2luZGV4",
            "X2xpc3QYBSADKAsyKC56cHJvdG8uUGF5T3JkZXJMaXN0Lk9yZGVySW5kZXhM",
            "aXN0RW50cnkSTwoXb3JkZXJfaW5kZXhfcmVmdW5kX2xpc3QYBiADKAsyLi56",
            "cHJvdG8uUGF5T3JkZXJMaXN0Lk9yZGVySW5kZXhSZWZ1bmRMaXN0RW50cnka",
            "NQoTT3JkZXJJbmRleExpc3RFbnRyeRILCgNrZXkYASABKAMSDQoFdmFsdWUY",
            "AiABKAU6AjgBGlMKGU9yZGVySW5kZXhSZWZ1bmRMaXN0RW50cnkSCwoDa2V5",
            "GAEgASgDEiUKBXZhbHVlGAIgASgLMhYuenByb3RvLlJlZnVuZEl0ZW1JbmZv",
            "OgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruPayDataReflection.Descriptor, global::Zproto.StruRefundItemInfoReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.PayOrderList), global::Zproto.PayOrderList.Parser, new[]{ "PayOrderList_", "PayRefundList", "FirstPay", "OrderIndexList", "OrderIndexRefundList" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayOrderList : pb::IMessage<PayOrderList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayOrderList> _parser = new pb::MessageParser<PayOrderList>(() => new PayOrderList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayOrderList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruPayOrderListReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayOrderList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayOrderList(PayOrderList other) : this() {
      payOrderList_ = other.payOrderList_.Clone();
      payRefundList_ = other.payRefundList_.Clone();
      firstPay_ = other.firstPay_ != null ? other.firstPay_.Clone() : null;
      orderIndexList_ = other.orderIndexList_.Clone();
      orderIndexRefundList_ = other.orderIndexRefundList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayOrderList Clone() {
      return new PayOrderList(this);
    }

    /// <summary>Field number for the "pay_order_list" field.</summary>
    public const int PayOrderList_FieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_payOrderList_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> payOrderList_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> PayOrderList_ {
      get { return payOrderList_; }
    }

    /// <summary>Field number for the "pay_refund_list" field.</summary>
    public const int PayRefundListFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_payRefundList_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> payRefundList_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> PayRefundList {
      get { return payRefundList_; }
    }

    /// <summary>Field number for the "first_pay" field.</summary>
    public const int FirstPayFieldNumber = 3;
    private global::Zproto.PayData firstPay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.PayData FirstPay {
      get { return firstPay_; }
      set {
        firstPay_ = value;
      }
    }

    /// <summary>Field number for the "order_index_list" field.</summary>
    public const int OrderIndexListFieldNumber = 5;
    private static readonly pbc::MapField<long, int>.Codec _map_orderIndexList_codec
        = new pbc::MapField<long, int>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForInt32(16, 0), 42);
    private readonly pbc::MapField<long, int> orderIndexList_ = new pbc::MapField<long, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, int> OrderIndexList {
      get { return orderIndexList_; }
    }

    /// <summary>Field number for the "order_index_refund_list" field.</summary>
    public const int OrderIndexRefundListFieldNumber = 6;
    private static readonly pbc::MapField<long, global::Zproto.RefundItemInfo>.Codec _map_orderIndexRefundList_codec
        = new pbc::MapField<long, global::Zproto.RefundItemInfo>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Zproto.RefundItemInfo.Parser), 50);
    private readonly pbc::MapField<long, global::Zproto.RefundItemInfo> orderIndexRefundList_ = new pbc::MapField<long, global::Zproto.RefundItemInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Zproto.RefundItemInfo> OrderIndexRefundList {
      get { return orderIndexRefundList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayOrderList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayOrderList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!payOrderList_.Equals(other.payOrderList_)) return false;
      if(!payRefundList_.Equals(other.payRefundList_)) return false;
      if (!object.Equals(FirstPay, other.FirstPay)) return false;
      if (!OrderIndexList.Equals(other.OrderIndexList)) return false;
      if (!OrderIndexRefundList.Equals(other.OrderIndexRefundList)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= payOrderList_.GetHashCode();
      hash ^= payRefundList_.GetHashCode();
      if (firstPay_ != null) hash ^= FirstPay.GetHashCode();
      hash ^= OrderIndexList.GetHashCode();
      hash ^= OrderIndexRefundList.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      payOrderList_.WriteTo(output, _repeated_payOrderList_codec);
      payRefundList_.WriteTo(output, _repeated_payRefundList_codec);
      if (firstPay_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FirstPay);
      }
      orderIndexList_.WriteTo(output, _map_orderIndexList_codec);
      orderIndexRefundList_.WriteTo(output, _map_orderIndexRefundList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      payOrderList_.WriteTo(ref output, _repeated_payOrderList_codec);
      payRefundList_.WriteTo(ref output, _repeated_payRefundList_codec);
      if (firstPay_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FirstPay);
      }
      orderIndexList_.WriteTo(ref output, _map_orderIndexList_codec);
      orderIndexRefundList_.WriteTo(ref output, _map_orderIndexRefundList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += payOrderList_.CalculateSize(_repeated_payOrderList_codec);
      size += payRefundList_.CalculateSize(_repeated_payRefundList_codec);
      if (firstPay_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FirstPay);
      }
      size += orderIndexList_.CalculateSize(_map_orderIndexList_codec);
      size += orderIndexRefundList_.CalculateSize(_map_orderIndexRefundList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayOrderList other) {
      if (other == null) {
        return;
      }
      payOrderList_.Add(other.payOrderList_);
      payRefundList_.Add(other.payRefundList_);
      if (other.firstPay_ != null) {
        if (firstPay_ == null) {
          FirstPay = new global::Zproto.PayData();
        }
        FirstPay.MergeFrom(other.FirstPay);
      }
      orderIndexList_.MergeFrom(other.orderIndexList_);
      orderIndexRefundList_.MergeFrom(other.orderIndexRefundList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            payOrderList_.AddEntriesFrom(input, _repeated_payOrderList_codec);
            break;
          }
          case 18: {
            payRefundList_.AddEntriesFrom(input, _repeated_payRefundList_codec);
            break;
          }
          case 26: {
            if (firstPay_ == null) {
              FirstPay = new global::Zproto.PayData();
            }
            input.ReadMessage(FirstPay);
            break;
          }
          case 42: {
            orderIndexList_.AddEntriesFrom(input, _map_orderIndexList_codec);
            break;
          }
          case 50: {
            orderIndexRefundList_.AddEntriesFrom(input, _map_orderIndexRefundList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            payOrderList_.AddEntriesFrom(ref input, _repeated_payOrderList_codec);
            break;
          }
          case 18: {
            payRefundList_.AddEntriesFrom(ref input, _repeated_payRefundList_codec);
            break;
          }
          case 26: {
            if (firstPay_ == null) {
              FirstPay = new global::Zproto.PayData();
            }
            input.ReadMessage(FirstPay);
            break;
          }
          case 42: {
            orderIndexList_.AddEntriesFrom(ref input, _map_orderIndexList_codec);
            break;
          }
          case 50: {
            orderIndexRefundList_.AddEntriesFrom(ref input, _map_orderIndexRefundList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
