// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_char_base_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_char_base_info.proto</summary>
  public static partial class StruCharBaseInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_char_base_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruCharBaseInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlzdHJ1X2NoYXJfYmFzZV9pbmZvLnByb3RvEgZ6cHJvdG8aFnN0cnVfYXZh",
            "dGFyX2luZm8ucHJvdG8aFHN0cnVfY2hhcl90ZWFtLnByb3RvGhZlbnVtX2Vf",
            "Ym9keV9zaXplLnByb3RvGhNlbnVtX2VfZ2VuZGVyLnByb3RvGhRzdHJ1X2Zh",
            "Y2VfZGF0YS5wcm90bxoXc3RydV9wcm9maWxlX2luZm8ucHJvdG8aFXN0cnVf",
            "dXNlcl91bmlvbi5wcm90bxoVc3RydV9kaXJ0eV9tYXNrLnByb3RvIrcHCgxD",
            "aGFyQmFzZUluZm8SDwoHY2hhcl9pZBgBIAEoAxISCgphY2NvdW50X2lkGAIg",
            "ASgJEg8KB3Nob3dfaWQYAyABKAMSEQoJc2VydmVyX2lkGAQgASgNEgwKBG5h",
            "bWUYBSABKAkSHwoGZ2VuZGVyGAYgASgOMg8uenByb3RvLkVHZW5kZXISEgoK",
            "aXNfZGVsZXRlZBgHIAEoCBIRCglpc19mb3JiaWQYCCABKAgSDwoHaXNfbXV0",
            "ZRgJIAEoCBIJCgF4GAogASgCEgkKAXkYCyABKAISCQoBehgMIAEoAhILCgNk",
            "aXIYDSABKAISIwoJZmFjZV9kYXRhGA4gASgLMhAuenByb3RvLkZhY2VEYXRh",
            "Eg8KB2NhcmRfaWQYDyABKA0SEwoLY3JlYXRlX3RpbWUYECABKAMSEwoLb25s",
            "aW5lX3RpbWUYESABKAMSFAoMb2ZmbGluZV90aW1lGBIgASgDEikKDHByb2Zp",
            "bGVfaW5mbxgTIAEoCzITLnpwcm90by5Qcm9maWxlSW5mbxIjCgl0ZWFtX2lu",
            "Zm8YFCABKAsyEC56cHJvdG8uQ2hhclRlYW0SEgoKY2hhcl9zdGF0ZRgVIAEo",
            "BBIkCglib2R5X3NpemUYFiABKA4yES56cHJvdG8uRUJvZHlTaXplEiUKCnVu",
            "aW9uX2luZm8YFyABKAsyES56cHJvdG8uVXNlclVuaW9uEhYKDnBlcnNvbmFs",
            "X3N0YXRlGBggAygFEicKC2F2YXRhcl9pbmZvGBkgASgLMhIuenByb3RvLkF2",
            "YXRhckluZm8SGQoRdG90YWxfb25saW5lX3RpbWUYGiABKAQSDwoHb3Blbl9p",
            "ZBgbIAEoCRIQCghzZGtfdHlwZRgcIAEoBRIKCgJvcxgdIAEoBRIaChJpbml0",
            "X3Byb2Zlc3Npb25faWQYHyABKAUSGwoTbGFzdF9jYWxfdG90YWxfdGltZRgg",
            "IAEoBBIPCgdhcmVhX2lkGCEgASgFEhYKDmNsaWVudF92ZXJzaW9uGCIgASgJ",
            "EhMKC2ZpZ2h0X3BvaW50GCMgASgFEhAKCHN1bV9zYXZlGCQgASgDEh8KF2Ns",
            "aWVudF9yZXNvdXJjZV92ZXJzaW9uGCUgASgJEhkKEWxhc3Rfb2ZmbGluZV90",
            "aW1lGCYgASgDEhgKEGRheV9hY2NfZHVyX3RpbWUYJyABKAUSHgoWbGFzdF9h",
            "Y2NfZHVyX3RpbWVzdGFtcBgoIAEoAxIYChBsYXN0X29ubGluZV90aW1lGCog",
            "ASgDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruAvatarInfoReflection.Descriptor, global::Zproto.StruCharTeamReflection.Descriptor, global::Zproto.EnumEBodySizeReflection.Descriptor, global::Zproto.EnumEGenderReflection.Descriptor, global::Zproto.StruFaceDataReflection.Descriptor, global::Zproto.StruProfileInfoReflection.Descriptor, global::Zproto.StruUserUnionReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.CharBaseInfo), global::Zproto.CharBaseInfo.Parser, new[]{ "CharId", "AccountId", "ShowId", "ServerId", "Name", "Gender", "IsDeleted", "IsForbid", "IsMute", "X", "Y", "Z", "Dir", "FaceData", "CardId", "CreateTime", "OnlineTime", "OfflineTime", "ProfileInfo", "TeamInfo", "CharState", "BodySize", "UnionInfo", "PersonalState", "AvatarInfo", "TotalOnlineTime", "OpenId", "SdkType", "Os", "InitProfessionId", "LastCalTotalTime", "AreaId", "ClientVersion", "FightPoint", "SumSave", "ClientResourceVersion", "LastOfflineTime", "DayAccDurTime", "LastAccDurTimestamp", "LastOnlineTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CharBaseInfo : pb::IMessage<CharBaseInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CharBaseInfo> _parser = new pb::MessageParser<CharBaseInfo>(() => new CharBaseInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CharBaseInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruCharBaseInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharBaseInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharBaseInfo(CharBaseInfo other) : this() {
      charId_ = other.charId_;
      accountId_ = other.accountId_;
      showId_ = other.showId_;
      serverId_ = other.serverId_;
      name_ = other.name_;
      gender_ = other.gender_;
      isDeleted_ = other.isDeleted_;
      isForbid_ = other.isForbid_;
      isMute_ = other.isMute_;
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      dir_ = other.dir_;
      faceData_ = other.faceData_ != null ? other.faceData_.Clone() : null;
      cardId_ = other.cardId_;
      createTime_ = other.createTime_;
      onlineTime_ = other.onlineTime_;
      offlineTime_ = other.offlineTime_;
      profileInfo_ = other.profileInfo_ != null ? other.profileInfo_.Clone() : null;
      teamInfo_ = other.teamInfo_ != null ? other.teamInfo_.Clone() : null;
      charState_ = other.charState_;
      bodySize_ = other.bodySize_;
      unionInfo_ = other.unionInfo_ != null ? other.unionInfo_.Clone() : null;
      personalState_ = other.personalState_.Clone();
      avatarInfo_ = other.avatarInfo_ != null ? other.avatarInfo_.Clone() : null;
      totalOnlineTime_ = other.totalOnlineTime_;
      openId_ = other.openId_;
      sdkType_ = other.sdkType_;
      os_ = other.os_;
      initProfessionId_ = other.initProfessionId_;
      lastCalTotalTime_ = other.lastCalTotalTime_;
      areaId_ = other.areaId_;
      clientVersion_ = other.clientVersion_;
      fightPoint_ = other.fightPoint_;
      sumSave_ = other.sumSave_;
      clientResourceVersion_ = other.clientResourceVersion_;
      lastOfflineTime_ = other.lastOfflineTime_;
      dayAccDurTime_ = other.dayAccDurTime_;
      lastAccDurTimestamp_ = other.lastAccDurTimestamp_;
      lastOnlineTime_ = other.lastOnlineTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharBaseInfo Clone() {
      return new CharBaseInfo(this);
    }

    /// <summary>Field number for the "char_id" field.</summary>
    public const int CharIdFieldNumber = 1;
    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { return charId_; }
      set {
        charId_ = value;
      }
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 2;
    private string accountId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "show_id" field.</summary>
    public const int ShowIdFieldNumber = 3;
    private long showId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ShowId {
      get { return showId_; }
      set {
        showId_ = value;
      }
    }

    /// <summary>Field number for the "server_id" field.</summary>
    public const int ServerIdFieldNumber = 4;
    private uint serverId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ServerId {
      get { return serverId_; }
      set {
        serverId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 5;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 6;
    private global::Zproto.EGender gender_ = global::Zproto.EGender.GenderNull;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EGender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "is_deleted" field.</summary>
    public const int IsDeletedFieldNumber = 7;
    private bool isDeleted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsDeleted {
      get { return isDeleted_; }
      set {
        isDeleted_ = value;
      }
    }

    /// <summary>Field number for the "is_forbid" field.</summary>
    public const int IsForbidFieldNumber = 8;
    private bool isForbid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsForbid {
      get { return isForbid_; }
      set {
        isForbid_ = value;
      }
    }

    /// <summary>Field number for the "is_mute" field.</summary>
    public const int IsMuteFieldNumber = 9;
    private bool isMute_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsMute {
      get { return isMute_; }
      set {
        isMute_ = value;
      }
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 10;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 11;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 12;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "dir" field.</summary>
    public const int DirFieldNumber = 13;
    private float dir_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Dir {
      get { return dir_; }
      set {
        dir_ = value;
      }
    }

    /// <summary>Field number for the "face_data" field.</summary>
    public const int FaceDataFieldNumber = 14;
    private global::Zproto.FaceData faceData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.FaceData FaceData {
      get { return faceData_; }
      set {
        faceData_ = value;
      }
    }

    /// <summary>Field number for the "card_id" field.</summary>
    public const int CardIdFieldNumber = 15;
    private uint cardId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CardId {
      get { return cardId_; }
      set {
        cardId_ = value;
      }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 16;
    private long createTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "online_time" field.</summary>
    public const int OnlineTimeFieldNumber = 17;
    private long onlineTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OnlineTime {
      get { return onlineTime_; }
      set {
        onlineTime_ = value;
      }
    }

    /// <summary>Field number for the "offline_time" field.</summary>
    public const int OfflineTimeFieldNumber = 18;
    private long offlineTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OfflineTime {
      get { return offlineTime_; }
      set {
        offlineTime_ = value;
      }
    }

    /// <summary>Field number for the "profile_info" field.</summary>
    public const int ProfileInfoFieldNumber = 19;
    private global::Zproto.ProfileInfo profileInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ProfileInfo ProfileInfo {
      get { return profileInfo_; }
      set {
        profileInfo_ = value;
      }
    }

    /// <summary>Field number for the "team_info" field.</summary>
    public const int TeamInfoFieldNumber = 20;
    private global::Zproto.CharTeam teamInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.CharTeam TeamInfo {
      get { return teamInfo_; }
      set {
        teamInfo_ = value;
      }
    }

    /// <summary>Field number for the "char_state" field.</summary>
    public const int CharStateFieldNumber = 21;
    private ulong charState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CharState {
      get { return charState_; }
      set {
        charState_ = value;
      }
    }

    /// <summary>Field number for the "body_size" field.</summary>
    public const int BodySizeFieldNumber = 22;
    private global::Zproto.EBodySize bodySize_ = global::Zproto.EBodySize.BodySizeNull;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EBodySize BodySize {
      get { return bodySize_; }
      set {
        bodySize_ = value;
      }
    }

    /// <summary>Field number for the "union_info" field.</summary>
    public const int UnionInfoFieldNumber = 23;
    private global::Zproto.UserUnion unionInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.UserUnion UnionInfo {
      get { return unionInfo_; }
      set {
        unionInfo_ = value;
      }
    }

    /// <summary>Field number for the "personal_state" field.</summary>
    public const int PersonalStateFieldNumber = 24;
    private static readonly pb::FieldCodec<int> _repeated_personalState_codec
        = pb::FieldCodec.ForInt32(194);
    private readonly pbc::RepeatedField<int> personalState_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> PersonalState {
      get { return personalState_; }
    }

    /// <summary>Field number for the "avatar_info" field.</summary>
    public const int AvatarInfoFieldNumber = 25;
    private global::Zproto.AvatarInfo avatarInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.AvatarInfo AvatarInfo {
      get { return avatarInfo_; }
      set {
        avatarInfo_ = value;
      }
    }

    /// <summary>Field number for the "total_online_time" field.</summary>
    public const int TotalOnlineTimeFieldNumber = 26;
    private ulong totalOnlineTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TotalOnlineTime {
      get { return totalOnlineTime_; }
      set {
        totalOnlineTime_ = value;
      }
    }

    /// <summary>Field number for the "open_id" field.</summary>
    public const int OpenIdFieldNumber = 27;
    private string openId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OpenId {
      get { return openId_; }
      set {
        openId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sdk_type" field.</summary>
    public const int SdkTypeFieldNumber = 28;
    private int sdkType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SdkType {
      get { return sdkType_; }
      set {
        sdkType_ = value;
      }
    }

    /// <summary>Field number for the "os" field.</summary>
    public const int OsFieldNumber = 29;
    private int os_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Os {
      get { return os_; }
      set {
        os_ = value;
      }
    }

    /// <summary>Field number for the "init_profession_id" field.</summary>
    public const int InitProfessionIdFieldNumber = 31;
    private int initProfessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int InitProfessionId {
      get { return initProfessionId_; }
      set {
        initProfessionId_ = value;
      }
    }

    /// <summary>Field number for the "last_cal_total_time" field.</summary>
    public const int LastCalTotalTimeFieldNumber = 32;
    private ulong lastCalTotalTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong LastCalTotalTime {
      get { return lastCalTotalTime_; }
      set {
        lastCalTotalTime_ = value;
      }
    }

    /// <summary>Field number for the "area_id" field.</summary>
    public const int AreaIdFieldNumber = 33;
    private int areaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AreaId {
      get { return areaId_; }
      set {
        areaId_ = value;
      }
    }

    /// <summary>Field number for the "client_version" field.</summary>
    public const int ClientVersionFieldNumber = 34;
    private string clientVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientVersion {
      get { return clientVersion_; }
      set {
        clientVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fight_point" field.</summary>
    public const int FightPointFieldNumber = 35;
    private int fightPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FightPoint {
      get { return fightPoint_; }
      set {
        fightPoint_ = value;
      }
    }

    /// <summary>Field number for the "sum_save" field.</summary>
    public const int SumSaveFieldNumber = 36;
    private long sumSave_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SumSave {
      get { return sumSave_; }
      set {
        sumSave_ = value;
      }
    }

    /// <summary>Field number for the "client_resource_version" field.</summary>
    public const int ClientResourceVersionFieldNumber = 37;
    private string clientResourceVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientResourceVersion {
      get { return clientResourceVersion_; }
      set {
        clientResourceVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_offline_time" field.</summary>
    public const int LastOfflineTimeFieldNumber = 38;
    private long lastOfflineTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastOfflineTime {
      get { return lastOfflineTime_; }
      set {
        lastOfflineTime_ = value;
      }
    }

    /// <summary>Field number for the "day_acc_dur_time" field.</summary>
    public const int DayAccDurTimeFieldNumber = 39;
    private int dayAccDurTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DayAccDurTime {
      get { return dayAccDurTime_; }
      set {
        dayAccDurTime_ = value;
      }
    }

    /// <summary>Field number for the "last_acc_dur_timestamp" field.</summary>
    public const int LastAccDurTimestampFieldNumber = 40;
    private long lastAccDurTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastAccDurTimestamp {
      get { return lastAccDurTimestamp_; }
      set {
        lastAccDurTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "last_online_time" field.</summary>
    public const int LastOnlineTimeFieldNumber = 42;
    private long lastOnlineTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastOnlineTime {
      get { return lastOnlineTime_; }
      set {
        lastOnlineTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CharBaseInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CharBaseInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharId != other.CharId) return false;
      if (AccountId != other.AccountId) return false;
      if (ShowId != other.ShowId) return false;
      if (ServerId != other.ServerId) return false;
      if (Name != other.Name) return false;
      if (Gender != other.Gender) return false;
      if (IsDeleted != other.IsDeleted) return false;
      if (IsForbid != other.IsForbid) return false;
      if (IsMute != other.IsMute) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Dir, other.Dir)) return false;
      if (!object.Equals(FaceData, other.FaceData)) return false;
      if (CardId != other.CardId) return false;
      if (CreateTime != other.CreateTime) return false;
      if (OnlineTime != other.OnlineTime) return false;
      if (OfflineTime != other.OfflineTime) return false;
      if (!object.Equals(ProfileInfo, other.ProfileInfo)) return false;
      if (!object.Equals(TeamInfo, other.TeamInfo)) return false;
      if (CharState != other.CharState) return false;
      if (BodySize != other.BodySize) return false;
      if (!object.Equals(UnionInfo, other.UnionInfo)) return false;
      if(!personalState_.Equals(other.personalState_)) return false;
      if (!object.Equals(AvatarInfo, other.AvatarInfo)) return false;
      if (TotalOnlineTime != other.TotalOnlineTime) return false;
      if (OpenId != other.OpenId) return false;
      if (SdkType != other.SdkType) return false;
      if (Os != other.Os) return false;
      if (InitProfessionId != other.InitProfessionId) return false;
      if (LastCalTotalTime != other.LastCalTotalTime) return false;
      if (AreaId != other.AreaId) return false;
      if (ClientVersion != other.ClientVersion) return false;
      if (FightPoint != other.FightPoint) return false;
      if (SumSave != other.SumSave) return false;
      if (ClientResourceVersion != other.ClientResourceVersion) return false;
      if (LastOfflineTime != other.LastOfflineTime) return false;
      if (DayAccDurTime != other.DayAccDurTime) return false;
      if (LastAccDurTimestamp != other.LastAccDurTimestamp) return false;
      if (LastOnlineTime != other.LastOnlineTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharId != 0L) hash ^= CharId.GetHashCode();
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (ShowId != 0L) hash ^= ShowId.GetHashCode();
      if (ServerId != 0) hash ^= ServerId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Gender != global::Zproto.EGender.GenderNull) hash ^= Gender.GetHashCode();
      if (IsDeleted != false) hash ^= IsDeleted.GetHashCode();
      if (IsForbid != false) hash ^= IsForbid.GetHashCode();
      if (IsMute != false) hash ^= IsMute.GetHashCode();
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (Dir != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Dir);
      if (faceData_ != null) hash ^= FaceData.GetHashCode();
      if (CardId != 0) hash ^= CardId.GetHashCode();
      if (CreateTime != 0L) hash ^= CreateTime.GetHashCode();
      if (OnlineTime != 0L) hash ^= OnlineTime.GetHashCode();
      if (OfflineTime != 0L) hash ^= OfflineTime.GetHashCode();
      if (profileInfo_ != null) hash ^= ProfileInfo.GetHashCode();
      if (teamInfo_ != null) hash ^= TeamInfo.GetHashCode();
      if (CharState != 0UL) hash ^= CharState.GetHashCode();
      if (BodySize != global::Zproto.EBodySize.BodySizeNull) hash ^= BodySize.GetHashCode();
      if (unionInfo_ != null) hash ^= UnionInfo.GetHashCode();
      hash ^= personalState_.GetHashCode();
      if (avatarInfo_ != null) hash ^= AvatarInfo.GetHashCode();
      if (TotalOnlineTime != 0UL) hash ^= TotalOnlineTime.GetHashCode();
      if (OpenId.Length != 0) hash ^= OpenId.GetHashCode();
      if (SdkType != 0) hash ^= SdkType.GetHashCode();
      if (Os != 0) hash ^= Os.GetHashCode();
      if (InitProfessionId != 0) hash ^= InitProfessionId.GetHashCode();
      if (LastCalTotalTime != 0UL) hash ^= LastCalTotalTime.GetHashCode();
      if (AreaId != 0) hash ^= AreaId.GetHashCode();
      if (ClientVersion.Length != 0) hash ^= ClientVersion.GetHashCode();
      if (FightPoint != 0) hash ^= FightPoint.GetHashCode();
      if (SumSave != 0L) hash ^= SumSave.GetHashCode();
      if (ClientResourceVersion.Length != 0) hash ^= ClientResourceVersion.GetHashCode();
      if (LastOfflineTime != 0L) hash ^= LastOfflineTime.GetHashCode();
      if (DayAccDurTime != 0) hash ^= DayAccDurTime.GetHashCode();
      if (LastAccDurTimestamp != 0L) hash ^= LastAccDurTimestamp.GetHashCode();
      if (LastOnlineTime != 0L) hash ^= LastOnlineTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (ShowId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ShowId);
      }
      if (ServerId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ServerId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Name);
      }
      if (Gender != global::Zproto.EGender.GenderNull) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Gender);
      }
      if (IsDeleted != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsDeleted);
      }
      if (IsForbid != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsForbid);
      }
      if (IsMute != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsMute);
      }
      if (X != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(Z);
      }
      if (Dir != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(Dir);
      }
      if (faceData_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(FaceData);
      }
      if (CardId != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(CardId);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteInt64(CreateTime);
      }
      if (OnlineTime != 0L) {
        output.WriteRawTag(136, 1);
        output.WriteInt64(OnlineTime);
      }
      if (OfflineTime != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(OfflineTime);
      }
      if (profileInfo_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(ProfileInfo);
      }
      if (teamInfo_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(TeamInfo);
      }
      if (CharState != 0UL) {
        output.WriteRawTag(168, 1);
        output.WriteUInt64(CharState);
      }
      if (BodySize != global::Zproto.EBodySize.BodySizeNull) {
        output.WriteRawTag(176, 1);
        output.WriteEnum((int) BodySize);
      }
      if (unionInfo_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(UnionInfo);
      }
      personalState_.WriteTo(output, _repeated_personalState_codec);
      if (avatarInfo_ != null) {
        output.WriteRawTag(202, 1);
        output.WriteMessage(AvatarInfo);
      }
      if (TotalOnlineTime != 0UL) {
        output.WriteRawTag(208, 1);
        output.WriteUInt64(TotalOnlineTime);
      }
      if (OpenId.Length != 0) {
        output.WriteRawTag(218, 1);
        output.WriteString(OpenId);
      }
      if (SdkType != 0) {
        output.WriteRawTag(224, 1);
        output.WriteInt32(SdkType);
      }
      if (Os != 0) {
        output.WriteRawTag(232, 1);
        output.WriteInt32(Os);
      }
      if (InitProfessionId != 0) {
        output.WriteRawTag(248, 1);
        output.WriteInt32(InitProfessionId);
      }
      if (LastCalTotalTime != 0UL) {
        output.WriteRawTag(128, 2);
        output.WriteUInt64(LastCalTotalTime);
      }
      if (AreaId != 0) {
        output.WriteRawTag(136, 2);
        output.WriteInt32(AreaId);
      }
      if (ClientVersion.Length != 0) {
        output.WriteRawTag(146, 2);
        output.WriteString(ClientVersion);
      }
      if (FightPoint != 0) {
        output.WriteRawTag(152, 2);
        output.WriteInt32(FightPoint);
      }
      if (SumSave != 0L) {
        output.WriteRawTag(160, 2);
        output.WriteInt64(SumSave);
      }
      if (ClientResourceVersion.Length != 0) {
        output.WriteRawTag(170, 2);
        output.WriteString(ClientResourceVersion);
      }
      if (LastOfflineTime != 0L) {
        output.WriteRawTag(176, 2);
        output.WriteInt64(LastOfflineTime);
      }
      if (DayAccDurTime != 0) {
        output.WriteRawTag(184, 2);
        output.WriteInt32(DayAccDurTime);
      }
      if (LastAccDurTimestamp != 0L) {
        output.WriteRawTag(192, 2);
        output.WriteInt64(LastAccDurTimestamp);
      }
      if (LastOnlineTime != 0L) {
        output.WriteRawTag(208, 2);
        output.WriteInt64(LastOnlineTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (ShowId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ShowId);
      }
      if (ServerId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ServerId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Name);
      }
      if (Gender != global::Zproto.EGender.GenderNull) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Gender);
      }
      if (IsDeleted != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsDeleted);
      }
      if (IsForbid != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsForbid);
      }
      if (IsMute != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsMute);
      }
      if (X != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(Z);
      }
      if (Dir != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(Dir);
      }
      if (faceData_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(FaceData);
      }
      if (CardId != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(CardId);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteInt64(CreateTime);
      }
      if (OnlineTime != 0L) {
        output.WriteRawTag(136, 1);
        output.WriteInt64(OnlineTime);
      }
      if (OfflineTime != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(OfflineTime);
      }
      if (profileInfo_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(ProfileInfo);
      }
      if (teamInfo_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(TeamInfo);
      }
      if (CharState != 0UL) {
        output.WriteRawTag(168, 1);
        output.WriteUInt64(CharState);
      }
      if (BodySize != global::Zproto.EBodySize.BodySizeNull) {
        output.WriteRawTag(176, 1);
        output.WriteEnum((int) BodySize);
      }
      if (unionInfo_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(UnionInfo);
      }
      personalState_.WriteTo(ref output, _repeated_personalState_codec);
      if (avatarInfo_ != null) {
        output.WriteRawTag(202, 1);
        output.WriteMessage(AvatarInfo);
      }
      if (TotalOnlineTime != 0UL) {
        output.WriteRawTag(208, 1);
        output.WriteUInt64(TotalOnlineTime);
      }
      if (OpenId.Length != 0) {
        output.WriteRawTag(218, 1);
        output.WriteString(OpenId);
      }
      if (SdkType != 0) {
        output.WriteRawTag(224, 1);
        output.WriteInt32(SdkType);
      }
      if (Os != 0) {
        output.WriteRawTag(232, 1);
        output.WriteInt32(Os);
      }
      if (InitProfessionId != 0) {
        output.WriteRawTag(248, 1);
        output.WriteInt32(InitProfessionId);
      }
      if (LastCalTotalTime != 0UL) {
        output.WriteRawTag(128, 2);
        output.WriteUInt64(LastCalTotalTime);
      }
      if (AreaId != 0) {
        output.WriteRawTag(136, 2);
        output.WriteInt32(AreaId);
      }
      if (ClientVersion.Length != 0) {
        output.WriteRawTag(146, 2);
        output.WriteString(ClientVersion);
      }
      if (FightPoint != 0) {
        output.WriteRawTag(152, 2);
        output.WriteInt32(FightPoint);
      }
      if (SumSave != 0L) {
        output.WriteRawTag(160, 2);
        output.WriteInt64(SumSave);
      }
      if (ClientResourceVersion.Length != 0) {
        output.WriteRawTag(170, 2);
        output.WriteString(ClientResourceVersion);
      }
      if (LastOfflineTime != 0L) {
        output.WriteRawTag(176, 2);
        output.WriteInt64(LastOfflineTime);
      }
      if (DayAccDurTime != 0) {
        output.WriteRawTag(184, 2);
        output.WriteInt32(DayAccDurTime);
      }
      if (LastAccDurTimestamp != 0L) {
        output.WriteRawTag(192, 2);
        output.WriteInt64(LastAccDurTimestamp);
      }
      if (LastOnlineTime != 0L) {
        output.WriteRawTag(208, 2);
        output.WriteInt64(LastOnlineTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (ShowId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ShowId);
      }
      if (ServerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ServerId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Gender != global::Zproto.EGender.GenderNull) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (IsDeleted != false) {
        size += 1 + 1;
      }
      if (IsForbid != false) {
        size += 1 + 1;
      }
      if (IsMute != false) {
        size += 1 + 1;
      }
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (Dir != 0F) {
        size += 1 + 4;
      }
      if (faceData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceData);
      }
      if (CardId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CardId);
      }
      if (CreateTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(CreateTime);
      }
      if (OnlineTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(OnlineTime);
      }
      if (OfflineTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(OfflineTime);
      }
      if (profileInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ProfileInfo);
      }
      if (teamInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TeamInfo);
      }
      if (CharState != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(CharState);
      }
      if (BodySize != global::Zproto.EBodySize.BodySizeNull) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) BodySize);
      }
      if (unionInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(UnionInfo);
      }
      size += personalState_.CalculateSize(_repeated_personalState_codec);
      if (avatarInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(AvatarInfo);
      }
      if (TotalOnlineTime != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(TotalOnlineTime);
      }
      if (OpenId.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(OpenId);
      }
      if (SdkType != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(SdkType);
      }
      if (Os != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Os);
      }
      if (InitProfessionId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(InitProfessionId);
      }
      if (LastCalTotalTime != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(LastCalTotalTime);
      }
      if (AreaId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(AreaId);
      }
      if (ClientVersion.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ClientVersion);
      }
      if (FightPoint != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(FightPoint);
      }
      if (SumSave != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(SumSave);
      }
      if (ClientResourceVersion.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ClientResourceVersion);
      }
      if (LastOfflineTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(LastOfflineTime);
      }
      if (DayAccDurTime != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(DayAccDurTime);
      }
      if (LastAccDurTimestamp != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(LastAccDurTimestamp);
      }
      if (LastOnlineTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(LastOnlineTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CharBaseInfo other) {
      if (other == null) {
        return;
      }
      if (other.CharId != 0L) {
        CharId = other.CharId;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.ShowId != 0L) {
        ShowId = other.ShowId;
      }
      if (other.ServerId != 0) {
        ServerId = other.ServerId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Gender != global::Zproto.EGender.GenderNull) {
        Gender = other.Gender;
      }
      if (other.IsDeleted != false) {
        IsDeleted = other.IsDeleted;
      }
      if (other.IsForbid != false) {
        IsForbid = other.IsForbid;
      }
      if (other.IsMute != false) {
        IsMute = other.IsMute;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      if (other.Dir != 0F) {
        Dir = other.Dir;
      }
      if (other.faceData_ != null) {
        if (faceData_ == null) {
          FaceData = new global::Zproto.FaceData();
        }
        FaceData.MergeFrom(other.FaceData);
      }
      if (other.CardId != 0) {
        CardId = other.CardId;
      }
      if (other.CreateTime != 0L) {
        CreateTime = other.CreateTime;
      }
      if (other.OnlineTime != 0L) {
        OnlineTime = other.OnlineTime;
      }
      if (other.OfflineTime != 0L) {
        OfflineTime = other.OfflineTime;
      }
      if (other.profileInfo_ != null) {
        if (profileInfo_ == null) {
          ProfileInfo = new global::Zproto.ProfileInfo();
        }
        ProfileInfo.MergeFrom(other.ProfileInfo);
      }
      if (other.teamInfo_ != null) {
        if (teamInfo_ == null) {
          TeamInfo = new global::Zproto.CharTeam();
        }
        TeamInfo.MergeFrom(other.TeamInfo);
      }
      if (other.CharState != 0UL) {
        CharState = other.CharState;
      }
      if (other.BodySize != global::Zproto.EBodySize.BodySizeNull) {
        BodySize = other.BodySize;
      }
      if (other.unionInfo_ != null) {
        if (unionInfo_ == null) {
          UnionInfo = new global::Zproto.UserUnion();
        }
        UnionInfo.MergeFrom(other.UnionInfo);
      }
      personalState_.Add(other.personalState_);
      if (other.avatarInfo_ != null) {
        if (avatarInfo_ == null) {
          AvatarInfo = new global::Zproto.AvatarInfo();
        }
        AvatarInfo.MergeFrom(other.AvatarInfo);
      }
      if (other.TotalOnlineTime != 0UL) {
        TotalOnlineTime = other.TotalOnlineTime;
      }
      if (other.OpenId.Length != 0) {
        OpenId = other.OpenId;
      }
      if (other.SdkType != 0) {
        SdkType = other.SdkType;
      }
      if (other.Os != 0) {
        Os = other.Os;
      }
      if (other.InitProfessionId != 0) {
        InitProfessionId = other.InitProfessionId;
      }
      if (other.LastCalTotalTime != 0UL) {
        LastCalTotalTime = other.LastCalTotalTime;
      }
      if (other.AreaId != 0) {
        AreaId = other.AreaId;
      }
      if (other.ClientVersion.Length != 0) {
        ClientVersion = other.ClientVersion;
      }
      if (other.FightPoint != 0) {
        FightPoint = other.FightPoint;
      }
      if (other.SumSave != 0L) {
        SumSave = other.SumSave;
      }
      if (other.ClientResourceVersion.Length != 0) {
        ClientResourceVersion = other.ClientResourceVersion;
      }
      if (other.LastOfflineTime != 0L) {
        LastOfflineTime = other.LastOfflineTime;
      }
      if (other.DayAccDurTime != 0) {
        DayAccDurTime = other.DayAccDurTime;
      }
      if (other.LastAccDurTimestamp != 0L) {
        LastAccDurTimestamp = other.LastAccDurTimestamp;
      }
      if (other.LastOnlineTime != 0L) {
        LastOnlineTime = other.LastOnlineTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
          case 24: {
            ShowId = input.ReadInt64();
            break;
          }
          case 32: {
            ServerId = input.ReadUInt32();
            break;
          }
          case 42: {
            Name = input.ReadString();
            break;
          }
          case 48: {
            Gender = (global::Zproto.EGender) input.ReadEnum();
            break;
          }
          case 56: {
            IsDeleted = input.ReadBool();
            break;
          }
          case 64: {
            IsForbid = input.ReadBool();
            break;
          }
          case 72: {
            IsMute = input.ReadBool();
            break;
          }
          case 85: {
            X = input.ReadFloat();
            break;
          }
          case 93: {
            Y = input.ReadFloat();
            break;
          }
          case 101: {
            Z = input.ReadFloat();
            break;
          }
          case 109: {
            Dir = input.ReadFloat();
            break;
          }
          case 114: {
            if (faceData_ == null) {
              FaceData = new global::Zproto.FaceData();
            }
            input.ReadMessage(FaceData);
            break;
          }
          case 120: {
            CardId = input.ReadUInt32();
            break;
          }
          case 128: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 136: {
            OnlineTime = input.ReadInt64();
            break;
          }
          case 144: {
            OfflineTime = input.ReadInt64();
            break;
          }
          case 154: {
            if (profileInfo_ == null) {
              ProfileInfo = new global::Zproto.ProfileInfo();
            }
            input.ReadMessage(ProfileInfo);
            break;
          }
          case 162: {
            if (teamInfo_ == null) {
              TeamInfo = new global::Zproto.CharTeam();
            }
            input.ReadMessage(TeamInfo);
            break;
          }
          case 168: {
            CharState = input.ReadUInt64();
            break;
          }
          case 176: {
            BodySize = (global::Zproto.EBodySize) input.ReadEnum();
            break;
          }
          case 186: {
            if (unionInfo_ == null) {
              UnionInfo = new global::Zproto.UserUnion();
            }
            input.ReadMessage(UnionInfo);
            break;
          }
          case 194:
          case 192: {
            personalState_.AddEntriesFrom(input, _repeated_personalState_codec);
            break;
          }
          case 202: {
            if (avatarInfo_ == null) {
              AvatarInfo = new global::Zproto.AvatarInfo();
            }
            input.ReadMessage(AvatarInfo);
            break;
          }
          case 208: {
            TotalOnlineTime = input.ReadUInt64();
            break;
          }
          case 218: {
            OpenId = input.ReadString();
            break;
          }
          case 224: {
            SdkType = input.ReadInt32();
            break;
          }
          case 232: {
            Os = input.ReadInt32();
            break;
          }
          case 248: {
            InitProfessionId = input.ReadInt32();
            break;
          }
          case 256: {
            LastCalTotalTime = input.ReadUInt64();
            break;
          }
          case 264: {
            AreaId = input.ReadInt32();
            break;
          }
          case 274: {
            ClientVersion = input.ReadString();
            break;
          }
          case 280: {
            FightPoint = input.ReadInt32();
            break;
          }
          case 288: {
            SumSave = input.ReadInt64();
            break;
          }
          case 298: {
            ClientResourceVersion = input.ReadString();
            break;
          }
          case 304: {
            LastOfflineTime = input.ReadInt64();
            break;
          }
          case 312: {
            DayAccDurTime = input.ReadInt32();
            break;
          }
          case 320: {
            LastAccDurTimestamp = input.ReadInt64();
            break;
          }
          case 336: {
            LastOnlineTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
          case 24: {
            ShowId = input.ReadInt64();
            break;
          }
          case 32: {
            ServerId = input.ReadUInt32();
            break;
          }
          case 42: {
            Name = input.ReadString();
            break;
          }
          case 48: {
            Gender = (global::Zproto.EGender) input.ReadEnum();
            break;
          }
          case 56: {
            IsDeleted = input.ReadBool();
            break;
          }
          case 64: {
            IsForbid = input.ReadBool();
            break;
          }
          case 72: {
            IsMute = input.ReadBool();
            break;
          }
          case 85: {
            X = input.ReadFloat();
            break;
          }
          case 93: {
            Y = input.ReadFloat();
            break;
          }
          case 101: {
            Z = input.ReadFloat();
            break;
          }
          case 109: {
            Dir = input.ReadFloat();
            break;
          }
          case 114: {
            if (faceData_ == null) {
              FaceData = new global::Zproto.FaceData();
            }
            input.ReadMessage(FaceData);
            break;
          }
          case 120: {
            CardId = input.ReadUInt32();
            break;
          }
          case 128: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 136: {
            OnlineTime = input.ReadInt64();
            break;
          }
          case 144: {
            OfflineTime = input.ReadInt64();
            break;
          }
          case 154: {
            if (profileInfo_ == null) {
              ProfileInfo = new global::Zproto.ProfileInfo();
            }
            input.ReadMessage(ProfileInfo);
            break;
          }
          case 162: {
            if (teamInfo_ == null) {
              TeamInfo = new global::Zproto.CharTeam();
            }
            input.ReadMessage(TeamInfo);
            break;
          }
          case 168: {
            CharState = input.ReadUInt64();
            break;
          }
          case 176: {
            BodySize = (global::Zproto.EBodySize) input.ReadEnum();
            break;
          }
          case 186: {
            if (unionInfo_ == null) {
              UnionInfo = new global::Zproto.UserUnion();
            }
            input.ReadMessage(UnionInfo);
            break;
          }
          case 194:
          case 192: {
            personalState_.AddEntriesFrom(ref input, _repeated_personalState_codec);
            break;
          }
          case 202: {
            if (avatarInfo_ == null) {
              AvatarInfo = new global::Zproto.AvatarInfo();
            }
            input.ReadMessage(AvatarInfo);
            break;
          }
          case 208: {
            TotalOnlineTime = input.ReadUInt64();
            break;
          }
          case 218: {
            OpenId = input.ReadString();
            break;
          }
          case 224: {
            SdkType = input.ReadInt32();
            break;
          }
          case 232: {
            Os = input.ReadInt32();
            break;
          }
          case 248: {
            InitProfessionId = input.ReadInt32();
            break;
          }
          case 256: {
            LastCalTotalTime = input.ReadUInt64();
            break;
          }
          case 264: {
            AreaId = input.ReadInt32();
            break;
          }
          case 274: {
            ClientVersion = input.ReadString();
            break;
          }
          case 280: {
            FightPoint = input.ReadInt32();
            break;
          }
          case 288: {
            SumSave = input.ReadInt64();
            break;
          }
          case 298: {
            ClientResourceVersion = input.ReadString();
            break;
          }
          case 304: {
            LastOfflineTime = input.ReadInt64();
            break;
          }
          case 312: {
            DayAccDurTime = input.ReadInt32();
            break;
          }
          case 320: {
            LastAccDurTimestamp = input.ReadInt64();
            break;
          }
          case 336: {
            LastOnlineTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
